# typed: true
# frozen_string_literal: true

# Source emission: turns the node tree into the generated module text.
# Mixed into Codegen — methods run with the generator instance state.
class GraphWeaver::Codegen
  module Emit
    include Kernel # for sorbet: hosts are Objects
    include GraphWeaver::Inflect

    private

    # The Relay convention — an operation whose only variable is a required
    # input object — reads better flattened: the input's fields become
    # execute's kwargs directly, and the wrapping level is rebuilt on the
    # wire. Multi-variable (or nullable-input) operations keep the
    # variable-per-kwarg surface.
    def flatten_input(variables)
      return unless variables.size == 1

      var = variables.first
      return unless var.required && var.node.is_a?(NonNull)

      input = var.node.of
      input if input.is_a?(InputNode)
    end

    def input_references(node)
      node.fields.filter_map do |field|
        child = field.node
        child = child.of while child.respond_to?(:of)
        child if child.is_a?(InputNode)
      end
    end

    # Input structs in dependency order (referenced types before their
    # referrers) so each emitted const names an already-defined class.
    # Cycles make that impossible — flagged so emission can forward-declare
    # every input class first, then reopen each to add its props.
    def ordered_inputs
      ordered = []
      seen = {} # node => :done | :visiting (bool_exp graphs get big)
      cyclic = T.let(false, T::Boolean)

      visit = lambda do |node|
        next if seen[node] == :done

        if seen[node] == :visiting
          cyclic = true
          next
        end

        seen[node] = :visiting
        input_references(node).each(&visit)
        seen[node] = :done
        ordered << node
      end
      @variable_inputs.each_value(&visit)

      [ordered, cyclic]
    end

      # Mapped-enum tables, generated enums, and input structs
      # (dependency-ordered, forward-declared when cyclic) — inline in the
      # module that needs them, or once in the shared inputs module.
      def emit_variable_types(out)
          @mapped_enums.each_value do |mapped|
            emit_mapped_enum(mapped, out, 1)
            out << ""
          end
          @variable_enums.each_value do |enum|
            emit_enum(enum, out, 1)
            out << ""
          end
          inputs, cyclic = ordered_inputs
          if cyclic
            # Recursive input types (Hasura bool_exp et al) reference each other,
            # so no definition order satisfies the runtime — forward-declare every
            # class empty, then let the full definitions below reopen with props.
            # eval'd so srb sees only the full bodies (reopening a T::Struct to
            # add props is a static error; adding them at runtime is fine).
            out << "  # runtime-only forward declarations: these input types reference"
            out << "  # each other, so the full definitions below need the constants"
            out << "  eval(<<~RUBY, binding, __FILE__, __LINE__ + 1)"
            inputs.each { |input| out << "    class #{input.class_name} < T::Struct; end" }
            out << "  RUBY"
            out << ""
          end
          inputs.each do |input|
            emit_input(input, out, 1)
            out << ""
          end
        end

      # In the shared-inputs workflow the variable types live once in the
      # inputs module; the query module aliases what it uses, so
      # AdoptQuery::AdoptionInput stays a real constant — and shared types
      # keep ONE identity across every module that touches them.
      # Only the shared names THIS module's emission references: variable
      # root types (and, when flattened, the root input's field types)
      # plus every mapped-enum table (result casting reads them too).
      # Nested types stay un-aliased — they live in the inputs module.
      def shared_alias_names(variables, flatten)
        nodes = variables.map(&:node)
        nodes += flatten.fields.map(&:node) if flatten

        names = @mapped_enums.each_value.flat_map { |m| ["#{m.const_prefix}_FROM_WIRE", "#{m.const_prefix}_TO_WIRE"] }
        nodes.each do |wrapped|
          node = T.let(wrapped, T.untyped)
          node = node.of while node.is_a?(NonNull) || node.is_a?(List)
          case node
          when EnumNode, InputNode then names << node.class_name
          end
        end
        names.uniq
      end

      def emit_shared_aliases(out, names)
        return if names.empty?

        names.each { |name| out << "  #{name} = #{@inputs_namespace}::#{name}" }
        out << ""
      end

      # The shared inputs artifact: header + everything emit_variable_types
      # covers, wrapped in the namespace module.
      def emit_inputs_module
        out = []
        out << "# typed: strict"
        out << "# frozen_string_literal: true"
        out << ""
        out << "# Generated by GraphWeaver — do not edit. Shared variable types for"
        out << "# this schema; query modules alias what they use."
        out << ""
        requires = @requires.uniq.sort
        if requires.any?
          requires.each { |req| out << "require #{req.inspect}" }
          out << ""
        end
        out << "module #{@module_name}"
        emit_variable_types(out)
        out << "end"

        out.join("\n") + "\n"
      end

    # The whole generated file: header, requires, the QUERY heredoc,
    # enum tables, input structs (dependency-ordered, forward-declared
    # when cyclic), the Result tree, and execute — assembled from the
    # generator's walked state.
    def emit_module(root, variables)
      flatten = flatten_input(variables)
      aliases = @inputs_namespace ? shared_alias_names(variables, flatten) : []

      out = []
      out << "# typed: strict"
      out << "# frozen_string_literal: true"
      out << ""
      out << "# Generated by GraphWeaver — do not edit."
      out << ""
      requires = @requires.uniq.sort
      if requires.any?
        requires.each { |req| out << "require #{req.inspect}" }
        out << ""
      end
      if aliases.any?
        # the aliases below need the shared module loaded (same directory
        # by the generate! convention)
        out << "require_relative \"inputs\""
        out << ""
      end
      out << "module #{@module_name}"
      out << "  extend T::Sig"
      out << ""
      # a GraphQL block string could contain a bare GRAPHQL line, which
      # would terminate the heredoc early — pick a delimiter the query
      # can't collide with
      delimiter = "GRAPHQL"
      delimiter += "_" while @query.match?(/^\s*#{delimiter}\s*$/)
      out << "  QUERY = T.let(<<~'#{delimiter}', String)"
      @query.each_line { |line| out << "    #{line}".rstrip }
      out << "  #{delimiter}"
      out << ""
      if @inputs_namespace
        emit_shared_aliases(out, aliases)
      else
        emit_variable_types(out)
      end
      emit_nested(root, out, 1)
      out << ""
      emit_execute(out, variables, flatten:)
      out << "end"

      out.join("\n") + "\n"
    end

    def emit_nested(node, out, indent)
      case node
      when UnionNode then emit_union(node, out, indent)
      when EnumNode then emit_enum(node, out, indent)
      else emit_object(node, out, indent)
      end
    end

    def emit_enum(node, out, indent)
      pad = "  " * indent

      out << "#{pad}class #{node.class_name} < T::Enum"
      out << "#{pad}  enums do"
      node.values.each do |value|
        out << "#{pad}    #{camelize(value.downcase)} = new(#{value.inspect})"
      end
      out << "#{pad}  end"
      out << "#{pad}end"
    end

    # module-level wire translation tables for an app-mapped enum
    def emit_mapped_enum(node, out, indent)
      pad = "  " * indent
      type = node.bare_type
      prefix = node.const_prefix

      out << "#{pad}# GraphQL enum #{node.graphql_name} <-> #{type} (registered mapping)"
      out << "#{pad}#{prefix}_FROM_WIRE = T.let({"
      node.mapping.each do |wire, member|
        out << "#{pad}  #{wire.inspect} => #{type}.deserialize(#{member.serialize.to_s.inspect}),"
      end
      out << "#{pad}}.freeze, T::Hash[String, #{type}])"
      out << "#{pad}#{prefix}_TO_WIRE = T.let(#{prefix}_FROM_WIRE.invert.freeze, T::Hash[#{type}, String])"
    end

    def emit_object(node, out, indent)
      pad = "  " * indent

      out << "#{pad}class #{node.class_name} < T::Struct"
      out << "#{pad}  extend T::Sig"
      out << "#{pad}  include GraphWeaver::Hints"
      node.mixins.each do |mixin|
        out << "#{pad}  include #{mixin} # registered for #{node.graphql_type}"
      end
      out << ""

      node.fields.filter_map { |field| field.node.nested }.each do |child|
        emit_nested(child, out, indent + 1)
        out << ""
      end

      node.fields.each do |field|
        out << "#{pad}  const :#{field.prop}, #{field.node.prop_type}"
      end

      out << ""
      out << "#{pad}  sig { params(data: T::Hash[String, T.untyped]).returns(#{node.class_name}) }"
      out << "#{pad}  def self.from_h(data)"
      out << "#{pad}    new("
      node.fields.each do |field|
        out << "#{pad}      #{field.prop}: #{field_cast(field)},"
      end
      out << "#{pad}    )"
      out << "#{pad}  rescue GraphWeaver::TypeError"
      out << "#{pad}    raise # already wrapped by a nested struct — keep the innermost context"
      out << "#{pad}  rescue TypeError, ArgumentError, KeyError => e"
      out << "#{pad}    raise GraphWeaver::TypeError.new(struct: self, error: e)"
      out << "#{pad}  end"
      out << "#{pad}end"
    end

    def emit_union(node, out, indent)
      pad = "  " * indent

      out << "#{pad}module #{node.class_name}"
      out << "#{pad}  extend T::Sig"
      out << ""

      node.members.each_value do |member|
        emit_object(member, out, indent + 1)
        out << ""
      end

      member_names = node.members.values.map(&:class_name)
      type_alias = member_names.size == 1 ? member_names.first : "T.any(#{member_names.join(", ")})"
      out << "#{pad}  Type = T.type_alias { #{type_alias} }"
      out << ""
      out << "#{pad}  sig { params(data: T::Hash[String, T.untyped]).returns(Type) }"
      out << "#{pad}  def self.from_h(data)"
      out << "#{pad}    case (typename = data.fetch(\"__typename\"))"
      node.members.each do |graphql_name, member|
        out << "#{pad}    when #{graphql_name.inspect} then #{member.class_name}.from_h(data)"
      end
      out << "#{pad}    else raise GraphWeaver::TypeError.new(struct: self, message: \"unexpected __typename: \#{typename}\")"
      out << "#{pad}    end"
      out << "#{pad}  end"
      out << "#{pad}end"
    end

    def emit_execute(out, variables, flatten: nil)
      out << "  @client = T.let(nil, T.untyped)"
      out << ""
      out << "  class << self"
      out << "    extend T::Sig"
      out << ""
      out << "    sig { params(client: T.untyped).void }"
      out << "    attr_writer :client"
      out << ""
      out << "    # default client (a GraphWeaver::Client or any transport) for"
      out << "    # execute: per-module override, else the app default"
      out << "    sig { returns(T.untyped) }"
      out << "    def client"
      out << "      @client || #{@client_const || "GraphWeaver.client!"}"
      out << "    end"
      out << "  end"
      out << ""

      # the kwarg surface: the input's fields when flattened, else one
      # kwarg per declared variable — typed identically either way. The
      # per-call client override rides as an optional POSITIONAL arg, so
      # variables keep the entire kwarg namespace (nothing is reserved).
      params = flatten ? flatten.fields.partition(&:required).flatten : variables

      sig_params = ["client: T.untyped"]
      sig_params += params.map do |param|
        bare = param.node.coerce? ? param.node.coerce_input_type : param.node.bare_type
        kwarg_type = param.required || bare == "T.untyped" ? bare : "T.nilable(#{bare})"
        "#{kwarg_name(param)}: #{kwarg_type}"
      end

      kwargs = ["client = nil"]
      kwargs += params.map { |param| param.required ? "#{kwarg_name(param)}:" : "#{kwarg_name(param)}: nil" }

      # execute returns the full envelope; execute! is the strict shortcut for
      # `execute(...).data!` — the typed result, or a raised QueryError.
      forward = (["client"] + params.map { |param| "#{kwarg_name(param)}: #{kwarg_name(param)}" }).join(", ")

      if flatten
        out << "  # $#{variables.first.wire}'s fields, flattened into kwargs (single input-object variable)"
      end
      out << "  sig { params(#{sig_params.join(", ")}).returns(GraphWeaver::Response[Result]) }"
      out << "  def self.execute(#{kwargs.join(", ")})"

      if flatten
        fields = flatten.fields.map { |field| "#{field.prop}:" }.join(", ")
        out << "    variables = {"
        out << "      #{variables.first.wire.inspect} => #{flatten.class_name}.coerce({ #{fields} }).serialize,"
        out << "    }"
      else
        required, optional = variables.partition(&:required)
        if required.empty?
          out << "    variables = {}"
        else
          out << "    variables = {"
          required.each do |var|
            out << "      #{var.wire.inspect} => #{variable_serialize(var)},"
          end
          out << "    }"
        end
        optional.each do |var|
          out << "    variables[#{var.wire.inspect}] = #{variable_serialize(var)} unless #{var.kwarg}.nil?"
        end
      end

      out << ""
      out << "    transport = GraphWeaver.resolve_transport(client || self.client)"
      out << "    raw = transport.execute(QUERY, variables: variables).to_h"
      out << "    GraphWeaver::Response[Result].new("
      out << "      data: (Result.from_h(raw[\"data\"]) if raw[\"data\"]),"
      out << "      errors: (raw[\"errors\"] || []).map { |e| GraphWeaver::GraphQLError.from_h(e) },"
      out << "      extensions: raw[\"extensions\"] || {},"
      out << "    )"
      out << "  end"
      out << ""
      out << "  sig { params(#{sig_params.join(", ")}).returns(Result) }"
      out << "  def self.execute!(#{kwargs.join(", ")})"
      out << "    execute(#{forward}).data!"
      out << "  end"
    end

    # a kwarg surface entry is a VarDef (.kwarg) or, when flattened, an
    # InputNode::Field (.prop)
    def kwarg_name(param)
      param.respond_to?(:kwarg) ? param.kwarg : param.prop
    end

    def variable_serialize(var)
      value = var.node.coerce? ? var.node.coerce(var.kwarg) : var.kwarg
      var.node.serialize_identity? ? value : var.node.serialize(value, 1)
    end

    def field_cast(field)
      node = field.node

      if node.non_null?
        raw = "data.fetch(#{field.key.inspect})"
        node.identity? ? raw : node.cast(raw, 1)
      else
        raw = "data[#{field.key.inspect}]"
        node.identity? ? raw : "#{raw}&.then { |v1| #{node.cast("v1", 2)} }"
      end
    end

    # A module-level T::Struct per input type: typed consts plus a FIELDS
    # table the GraphWeaver::InputStruct runtime drives — serialize/to_h/
    # coerce live once in the gem, not unrolled per struct (bool_exp
    # schemas pull hundreds of inputs into one module).
    def emit_input(node, out, indent)
      pad = "  " * indent

      out << "#{pad}class #{node.class_name} < T::Struct"
      out << "#{pad}  include GraphWeaver::InputStruct"
      out << "#{pad}  extend GraphWeaver::InputStruct::ClassMethods"
      out << ""
      node.fields.each do |field|
        default = field.required ? "" : ", default: nil"
        out << "#{pad}  const :#{field.prop}, #{field.node.prop_type}#{default}"
      end
      out << ""
      out << "#{pad}  # (prop, wire, required, serializer, coercer) per field"
      out << "#{pad}  FIELDS = T.let(["
      node.fields.each do |field|
        serializer = field.node.serialize_identity? ? "nil" : "->(v) { #{field.node.serialize("v", 1)} }"
        coercer = field.node.hash_coerce_identity? ? "nil" : "->(v) { #{field.node.hash_coerce("v", 1)} }"
        out << "#{pad}    GraphWeaver::InputStruct::Field.new(:#{field.prop}, #{field.wire.inspect}, #{field.required}, #{serializer}, #{coercer}),"
      end
      out << "#{pad}  ].freeze, T::Array[GraphWeaver::InputStruct::Field])"
      out << "#{pad}end"
    end
  end
end
