#!/usr/bin/env ruby
# typed: false
# frozen_string_literal: true

# Regenerate the checked-in typed modules from queries/*.graphql —
# the same workflow `rake graph_weaver:generate` runs in an app:
#
#      examples/github/generate.rb
#
# bin/generate calls generate! too, off the cached dump, so these files are
# regenerated by the build like every other checked-in generated file.
require_relative "setup"

module GithubExample
  # The graph, declared once for both doors: this script, which introspects
  # GitHub, and bin/generate, which passes the dump that introspection cached.
  def self.generate!(schema_source)
    GraphWeaver.graph :github do
      schema schema_source
      queries File.join(__dir__, "queries")
      output File.join(__dir__, "generated")
    end

    GraphWeaver.generate!
    GraphWeaver.changed_files
  end
end

if $PROGRAM_NAME == __FILE__
  GithubExample.connect!
  changed = GithubExample.generate!(GraphWeaver.client.schema)
  changed.each { |path| puts "wrote #{path}" }
  puts "already up to date" if changed.empty?
end
