require "graphql"
require "sorbet-runtime"

require_relative "graph_weaver/logging"
require_relative "graph_weaver/errors"
require_relative "graph_weaver/hints"
require_relative "graph_weaver/input_struct"
require_relative "graph_weaver/query_module"
require_relative "graph_weaver/response"
require_relative "graph_weaver/inflect"
require_relative "graph_weaver/codegen"
require_relative "graph_weaver/client"
require_relative "graph_weaver/in_process"
require_relative "graph_weaver/transport/http"
require_relative "graph_weaver/retry"
require_relative "graph_weaver/schema_loader"
require_relative "graph_weaver/version"
require_relative "graph_weaver/railtie" if defined?(::Rails::Railtie)

# opt-in extras:
#      require "graph_weaver/transport/faraday"        # Faraday transport
module GraphWeaver
  # The line every generated file opens with (see Codegen::Emit) — the marker
  # that tells generate! which files in the output directory are its to prune.
  GENERATED_HEADER = "# Generated by GraphWeaver"

  # How far into a file to look for it: the header sits under the `typed:` and
  # `frozen_string_literal:` magic comments, never deeper.
  HEADER_SCAN_LINES = 10

  class << self
    # A client for one GraphQL server — transport, schema, and scoped
    # scalars in one object (see Client):
    #
    #      github = GraphWeaver.new("https://api.github.com/graphql", auth: token, cache: true)
    #      RepoQuery = github.parse("queries/repo.graphql")
    #
    # The first argument is a url or any schema source (a live schema
    # class, or a path/SDL/introspection dump).
    def new(source, **options, &middleware)
      check_source!(source)
      Client.new(source, **options, &middleware)
    end

    # Anything already speaking the client contract — InProcess, Retry, a
    # transport, a fake, the test router — carries no schema to generate
    # from, so it can't stand in as the schema source. Without this it is
    # handed to SchemaLoader and fails as `undefined method 'lstrip'`.
    def check_source!(source)
      # a graphql-ruby schema class executes too, and *is* a schema source
      return if source.is_a?(Module) || !source.respond_to?(:execute)

      raise Error, "#{source.class} is a client, not a schema source — pass the schema, and this " \
        "as its transport: GraphWeaver.new(schema, transport: client). For a live schema class " \
        "with a context: GraphWeaver.new(schema, context: { ... })."
    end
    private :check_source!

    # The app's default client — how generated modules find their server:
    #
    #      GraphWeaver.client = GraphWeaver.new(url, auth: token)
    #
    # Accepts a Client or anything satisfying the execute contract (a
    # schema class, a fake — testing's graphql: tag swaps one in per
    # example). Generated modules resolve per call -> per module
    # (MyQuery.client=) -> baked constant -> here.
    attr_accessor :client

    # the default client, when one is required
    def client!
      @client or raise Error, "no client configured — set GraphWeaver.client= or pass a client"
    end

    # The transport behind a client-or-transport value: a Client resolves
    # to its own transport, anything else already speaks execute.
    # Generated modules call this on every execute, so any slot in the
    # resolution chain can hold either kind.
    def resolve_transport(target)
      return target.transport! if target.is_a?(Client)
      unless target.respond_to?(:execute)
        raise Error, "client must respond to #execute(query, variables:), got #{target.class}"
      end

      target
    end

    # Shape-check a raw response envelope, returning it. Generated
    # from_response is public API taking anything with #to_h, so a malformed
    # body has to brand rather than escape as a raw Sorbet TypeError from a sig
    # (which fires before the struct's own rescue can see it). Lives here rather
    # than unrolled into every generated module.
    def check_envelope!(raw, struct)
      unless raw.is_a?(Hash)
        raise GraphWeaver::TypeError.new(struct:, message: "response must be an object, got #{raw.class}")
      end

      %w[data extensions].each do |key|
        value = raw[key]
        next if value.nil? || value.is_a?(Hash)

        raise GraphWeaver::TypeError.new(struct:, message: "response #{key.inspect} must be an object, got #{value.class}")
      end

      errors = raw["errors"]
      unless errors.nil? || (errors.is_a?(Array) && errors.all?(Hash))
        raise GraphWeaver::TypeError.new(struct:, message: "response \"errors\" must be an array of objects")
      end

      raw
    end

    # The module a .graphql file generates, and the basename of the file it
    # generates into: the camelized file name plus the operation's own word.
    #
    #      person.graphql          => PersonQuery       (person_query.rb)
    #      save_list_entry.graphql => SaveListEntryMutation
    #                                 (save_list_entry_mutation.rb)
    #
    # Every naming site goes through here — generate!, parse(path), and
    # load_queries! — so the constant a file produces is the same one
    # whichever door you came in by.
    def module_name(path, source)
      "#{Inflect.camelize(File.basename(path, ".*"))}#{operation_suffix(source)}"
    end

    # "Mutation" for a mutation document, "Query" for everything else.
    def operation_suffix(source)
      operation = GraphQL.parse(source).definitions
        .grep(GraphQL::Language::Nodes::OperationDefinition).first
      (operation&.operation_type == "mutation") ? "Mutation" : "Query"
    rescue GraphQL::ParseError
      "Query" # unparseable: codegen brands the real error a moment later
    end

    # Conventional locations. generated_paths and fragments_paths are LISTS,
    # factory_bot-style, so extra locations (a test-only dir, an engine's) can
    # be appended and every loader walks them all — entries may be glob
    # patterns, and the generated default already matches per-schema layouts
    # (app/graphql/github/generated):
    #
    #      # e.g. in spec/support/graph_weaver.rb
    #      GraphWeaver.generated_paths << "spec/support/graphql/generated"
    #
    # Queries are SINGULAR. One generate! run reads one directory against one
    # schema, so a second one would produce modules at runtime that
    # `rake graph_weaver:generate` never generates and `verify` never checks.
    attr_writer :generated_paths, :schema_path, :fragments_paths
    attr_accessor :queries_path

    def queries_path = @queries_path ||= "app/graphql/queries"
    def generated_paths = @generated_paths ||= ["app/graphql/generated", "app/graphql/*/generated"]

    # Reusable named fragments, defined once and available to every query —
    # each query inlines only the ones it (transitively) spreads, so the sent
    # query stays self-contained.
    def fragments_paths = @fragments_paths ||= ["app/graphql/fragments"]

    # the singular readers take the first entry — the default target for
    # generate! and the rake tasks; assigning one replaces the list
    def generated_path = generated_paths.first
    def fragments_path = fragments_paths.first

    def generated_path=(path)
      @generated_paths = path.nil? ? nil : [path]
    end

    def schema_path = @schema_path || "app/graphql/schema.json"

    # The name of the shared module — the types that live once per schema
    # (input types, enums, unions hoisted from shared fragments) and are
    # aliased into every query module that touches them. Constant, not derived
    # from where you put the files: set it globally, or pass types_module: per
    # generate!. A multi-schema layout names it in the same initializer that
    # sets its paths.
    attr_writer :types_module

    def types_module = @types_module || "GraphQLTypes"

    # Generate every query in a directory — .graphql/.gql, subdirectories
    # included — into checked-in Ruby files. Paths default to the conventions
    # above; schema: defaults to the dump at schema_path (any supported
    # extension), and also takes a Client (its schema — the console object,
    # no dump needed):
    #
    #      GraphWeaver.generate!   # queries_path -> generated_path
    #
    # person.graphql => person_query.rb defining PersonQuery. Returns the
    # written paths. Generated files the plan no longer produces are deleted
    # (see #orphaned), so renaming or dropping a .graphql leaves nothing
    # behind. Pair with a freshness spec (docs/generated_modules.md).
    def generate!(schema: nil, queries: queries_path, output: generated_path, client: nil,
      types_module: nil)
      schema = schema ? schema_for(schema) : locate_schema!

      plan = generation_plan(queries:, schema:, client:, types_module:)
      written = plan.map do |filename, source|
        target = File.join(output, filename)
        FileUtils.mkdir_p(File.dirname(target))
        File.write(target, source)
        log(:info) { "generated #{target}" }
        target
      end

      orphaned(output, written).each do |orphan|
        File.delete(orphan)
        log(:info) { "pruned #{orphan}" }
      end

      written
    end

    # Generated files under output the current plan no longer produces — a
    # query renamed or deleted, a type dropped from the schema, a union no
    # longer hoisted. Left alone they'd keep being required by
    # load_generated!, resolving against a query that no longer exists.
    def orphaned(output, produced)
      current = produced.map { |path| File.expand_path(path) }
      generated_files(output).reject { |path| current.include?(File.expand_path(path)) }
    end
    private :orphaned

    # Every .rb under output that GraphWeaver wrote, identified by the header
    # it emits. The header — not a *_query.rb glob — is what makes pruning
    # safe: this is a real directory, and a hand-written file in it must
    # survive regeneration.
    def generated_files(output)
      Dir[File.join(output, "**/*.rb")].sort.select do |path|
        File.foreach(path).first(HEADER_SCAN_LINES).any? { |line| line.start_with?(GENERATED_HEADER) }
      end
    end
    private :generated_files

    # The freshness guard: raise unless every generated file matches what
    # the current schema + queries + scalar registrations would produce —
    # counting a generated file the plan no longer produces as stale, so a
    # deleted query can't leave a live module behind. One line in a spec, or
    # `rake graph_weaver:verify` in CI:
    #
    #      it "generated queries are current" do
    #        GraphWeaver.verify_generated!
    #      end
    def verify_generated!(schema: nil, queries: queries_path, output: generated_path, client: nil,
      types_module: nil)
      schema = schema ? schema_for(schema) : locate_schema!
      plan = generation_plan(queries:, schema:, client:, types_module:)
      stale = plan.filter_map do |filename, source|
        target = File.join(output, filename)
        # git's autocrlf rewrites line endings on checkout — a Windows working
        # copy is not stale generated code, so don't fail CI over it
        target unless File.exist?(target) && File.read(target).gsub("\r\n", "\n") == source.gsub("\r\n", "\n")
      end
      # strays: a generated file the current schema + queries no longer produce
      stale += orphaned(output, plan.map { |filename, _| File.join(output, filename) })

      unless stale.empty?
        raise Error, "stale generated queries — regenerate (rake graph_weaver:generate): #{stale.join(", ")}"
      end

      true
    end

    # Which checked-in queries no longer validate — breaking-change
    # detection scoped to the operations you actually ship. Reports rather
    # than raising, keyed by file, JSON-ready like every #to_h here:
    #
    #      GraphWeaver.check_queries
    #      # => { "app/graphql/queries/person.graphql" =>
    #      #      [{ "message" => "Field 'titel' doesn't exist on type 'Person'",
    #      #         "line" => 4, "column" => 5 }] }
    #
    # Empty means every query validates. schema: defaults to the server as
    # it is now — a FRESH introspection of the url the dump records, or the
    # live schema class when the app default runs in-process — and the dump
    # is left alone; pass schema: and nothing touches the network.
    #
    # When that dump is a composed supergraph, an error naming a type is
    # branded with the subgraphs behind it — "…on type 'Product'
    # (products, reviews)", plus a "subgraphs" key — since knowing whose
    # code to look at is half the answer. A plain schema is unaffected.
    #
    # A different question from verify_generated!, which asks whether the
    # committed Ruby matches the committed schema. `rake
    # graph_weaver:queries:check` prints this and exits non-zero.
    def check_queries(schema: nil, queries: queries_path, fragments: fragments_paths)
      table = schema ? nil : checked_routing_table
      schema = schema ? schema_for(schema) : refreshed_schema
      shared = Codegen.load_fragments(fragments)

      Dir[File.join(queries, Codegen::DOCUMENT_GLOB)].sort.each_with_object({}) do |path, failures|
        errors = validation_errors(schema, File.read(path), shared, table)
        failures[path] = errors if errors.any?
      end
    end

    # The routing table behind the schema check_queries is about to use,
    # when there is one: a composed supergraph dump says who resolves what,
    # so a validation error can name the subgraph whose code to look at. nil
    # for every other source — a plain schema is entirely unaffected — and
    # nil when a live schema class is what gets checked, since the dump then
    # isn't what the errors came from.
    def checked_routing_table
      return if live_schema

      path = SchemaLoader.locate_path
      return unless path&.end_with?(".graphql", ".gql")

      sdl = File.read(path)
      SchemaLoader.routing_table(sdl) if SchemaLoader.federation_sdl?(sdl)
    end
    private :checked_routing_table

    # The schema check_queries defaults to: the server as it is now. Over a
    # socket that's a fresh introspection of the url the local dump recorded,
    # so no refresh step (and no rewritten dump) is needed first. In-process
    # it's the live schema class — for an app that IS the server, a dump is a
    # snapshot of its own code, and checking against it reports phantom
    # errors about a field you just added. Dumps with no url and no live
    # class — hand-written SDL, a composed supergraph — have nothing to
    # re-read, so they're checked as they are.
    def refreshed_schema
      live = live_schema
      return live if live

      # locate_schema! raises the conventional "no schema dump" message
      path = SchemaLoader.locate_path or locate_schema!
      meta = SchemaLoader.provenance(path)
      return SchemaLoader.load(path) unless meta&.key?("url")

      SchemaLoader.introspect(new(meta["url"], auth: ENV["GRAPHWEAVER_AUTH"]).transport)
    end
    private :refreshed_schema

    # The graphql-ruby schema class the app default executes against, when it
    # runs in-process — a Client wrapping one, or the class in the slot bare.
    # nil for every network client. Not memoized: in dev the class object is
    # replaced on reload. (Public because testing's :in_process mode asks:
    # a client already running in-process names its own schema class.)
    def live_schema
      target = client.is_a?(Client) ? client.transport : client
      target = target.schema if target.is_a?(InProcess)
      target if target.is_a?(Class) && target <= GraphQL::Schema
    end

    # One query's schema-validation errors as JSON-ready hashes, with the
    # source position graphql-ruby reports. Unparseable counts as an error
    # too — it doesn't validate either, and inline_fragments (which parses
    # first) has already branded it with its position.
    def validation_errors(schema, source, shared, table = nil)
      # path omitted: the caller keys the report by file, so branding the
      # message with it too would just print the path twice
      schema.validate(Codegen.inline_fragments(source, shared)).map do |error|
        detail = error.to_h
        location = detail["locations"]&.first || {}
        subgraphs = table ? attribute(table, detail["extensions"]) : []
        entry = {
          "message" => subgraphs.empty? ? error.message : "#{error.message} (#{subgraphs.join(", ")})",
          "line" => location["line"],
          "column" => location["column"],
        }
        subgraphs.empty? ? entry : entry.merge("subgraphs" => subgraphs)
      end
    rescue GraphWeaver::ValidationError => e
      e.errors.map { |detail| detail.transform_keys(&:to_s) }
    end
    private :validation_errors

    # Which subgraphs a validation error is about, on a federated schema:
    # "Field 'weight' doesn't exist on type 'Product'" is much less useful
    # than the same line plus "(products)" — whose code to look at, whose
    # team to talk to. graphql-ruby reports the coordinate structurally, so
    # this is a lookup rather than message parsing. Both halves of the
    # coordinate are required: an argument error reports typeName "Field"
    # (the AST node kind, not a type), and looking that up would attribute
    # confidently and wrongly.
    def attribute(table, extensions)
      return [] unless extensions

      type_name, field_name = extensions.values_at("typeName", "fieldName")
      return [] unless type_name && field_name

      table.responsible(type_name, field_name)
    end
    private :attribute

    # Load the generated modules — one line in an initializer or spec
    # helper (loading happens only when you call this; skip it and
    # require files yourself if you'd rather):
    #
    #      GraphWeaver.load_generated!
    #
    # In Rails, prefer this over autoloading: Zeitwerk would expect
    # Generated::PersonQuery from generated/person_query.rb, and
    # generated code only changes on regeneration anyway (restart, like
    # a schema migration).
    def load_generated!(path = nil)
      paths = path ? [path] : generated_paths
      files = paths.flat_map { |dir| Dir[File.join(dir, "**/*.rb")].sort }.uniq
      files.each { |file| require File.expand_path(file) }
      log(:info) { "loaded #{files.size} generated module(s) from #{paths.join(", ")}" }
      files
    end

    # Anywhere GraphWeaver takes schema:, a Client stands for its schema — so
    # the console object and the rake task point at the same thing.
    # a Client carries one; a path or SDL string loads like it does everywhere
    # else in the library (a String reached `schema.validate` as itself before,
    # and failed as `undefined method 'validate' for an instance of String`)
    def schema_for(source)
      case source
      when Client then source.schema
      when String then SchemaLoader.load(source)
      else source
      end
    end
    private :schema_for

    # the conventional schema dump, required
    def locate_schema!
      SchemaLoader.locate or raise Error,
        "no schema dump at #{schema_path} (.json/.graphql/.gql) — pass schema:, or cache one: GraphWeaver.new(url, cache: true).schema"
    end
    private :locate_schema!

    # (filename, source) per artifact. Types a schema shares across queries —
    # input types, schema enums, and each named shared fragment spread as a
    # whole-union field — are emitted once into the shared module, with query
    # modules aliasing what they use. That's the difference between hundreds of
    # duplicated bool_exp structs (or one Ruby class per query for the same
    # schema enum) and one copy per schema. (Single-query parse inlines
    # everything — there's no cross-query set to share against.)
    def generation_plan(queries:, schema:, client:, types_module: nil, fragments: fragments_paths)
      types_module ||= self.types_module
      used = { inputs: [], enums: [], mapped: [] }
      used_unions = []
      shared = Codegen.load_fragments(fragments)

      seen = {} # module name => the file that produced it, for the collision message

      plan = Dir[File.join(queries, Codegen::DOCUMENT_GLOB)].sort.map do |path|
        base = File.basename(path, File.extname(path))
        source = File.read(path)
        suffix = operation_suffix(source)
        name = "#{Inflect.camelize(base)}#{suffix}"
        if (earlier = seen[name])
          raise Error, "duplicate query module #{name} — #{earlier} and #{path} both generate it; " \
            "the module name comes from the file name alone (directories don't namespace it), so rename one"
        end
        seen[name] = path

        codegen = Codegen.new(
          schema:,
          query: Codegen.inline_fragments(source, shared, path),
          module_name: name,
          client:,
          types_namespace: types_module,
          hoistable_unions: Codegen.shared_fragment_spreads(source, shared, path),
          path:,
        )
        out = codegen.generate
        codegen.variable_type_names.each { |kind, names| used[kind] |= names }
        used_unions |= codegen.used_union_names
        ["#{base}_#{suffix.downcase}.rb", out]
      end

      if used_unions.any? || used.values.any?(&:any?)
        codegen = Codegen.new(schema:, query: "", module_name: types_module)
        plan = codegen.generate_types(
          inputs: used[:inputs], enums: used[:enums] + used[:mapped],
          unions: used_unions, fragments: shared,
        ).to_a + plan
      end

      plan
    end
    private :generation_plan

    # Default input coercion for scalars that don't say coerce: themselves,
    # resolved lazily at generation time (so set it any time before you
    # generate — no reset_scalars! ordering dance):
    #
    #      GraphWeaver.auto_coerce = true
    #
    # Convertible built-ins take their conversion (Int accepts 5/"5"),
    # and any scalar with a full cast/serialize pair (Date, your Money)
    # accepts its raw wire form. An explicit coerce: true/false/Symbol on
    # a registration always wins.
    attr_accessor :auto_coerce

    # Whether generated modules/structs emit `extend T::Sig` (so `sig`
    # resolves standalone). Default (nil) auto-detects: an app that globally
    # injects T::Sig (`class Module; include T::Sig`) makes the per-struct
    # extend redundant — rubocop's Sorbet/RedundantExtendTSig flags it — so
    # generation skips it. Force with true/false. Resolved at generation time.
    #
    #      GraphWeaver.extend_t_sig = false   # never emit (rely on a global include)
    attr_writer :extend_t_sig

    # The resolved boolean codegen uses: the explicit setting, else emit
    # unless T::Sig is globally injected into Module.
    def extend_t_sig?
      @extend_t_sig.nil? ? !global_tsig? : @extend_t_sig
    end

    # Whether the host app has globally injected T::Sig into every module
    # (`class Module; include T::Sig`) — extracted so it's stubbable in tests.
    def global_tsig? = Module.include?(T::Sig)

    # The closest entry in `dictionary` to `term` — a "did you mean" suggestion,
    # or nil (also nil when did_you_mean isn't loadable). One home for the guard
    # used by codegen validation, alias resolution, and the runtime prop hints.
    def did_you_mean(dictionary, term)
      return unless defined?(DidYouMean::SpellChecker)

      DidYouMean::SpellChecker.new(dictionary: dictionary).correct(term).first
    end

    # Teach the generator how a GraphQL custom scalar deserializes into a
    # rich Ruby object (and serializes back onto the wire when used as a
    # variable):
    #
    #      GraphWeaver.register_scalar("Money", Money, requires: "bigdecimal")
    #
    # A field typed `Money` then generates `const :price, T.nilable(Money)`
    # and casts with `Money.parse(...)` in from_h. Pass a real class as
    # type: and cast:/serialize: are inferred from it — .parse/#to_s, or
    # .load/.dump — by probing the deserialize side (see ScalarType::CODECS).
    # Override with a Symbol method name (safest — no string to misspell), a
    # Proc(expr) => code string, or :itself to force pass-through. requires:
    # (a String or Array) names files the generated code needs — validated,
    # and actually required to confirm it resolves when type: is a real class.
    # coerce: true makes a variable of this scalar accept the value OR its
    # raw input (e.g. "12.00"), running the latter through the cast before
    # serializing — it raises on bad input, so some safety survives. Built-in
    # scalars are pre-registered the same way, so this also overrides them.
    #
    # Pass a `Type.field` coordinate instead of a scalar name to override just
    # that one field — so the same scalar can deserialize as different Ruby
    # types across fields (a `Date` for `User.birthday`, a `Time` elsewhere):
    #
    #      GraphWeaver.register_scalar("User.birthday", Date)
    #
    # A field-level override wins over the scalar-name registration. Same
    # signature either way. Call before generating.
    def register_scalar(graphql_name, type, cast: nil, serialize: nil, requires: nil, coerce: nil)
      Codegen.register_scalar(graphql_name, type, cast:, serialize:, requires:, coerce:)
    end

    # Map a GraphQL enum onto an app-owned T::Enum, so generated code
    # speaks YOUR enum — casting wire values in, serializing members out:
    #
    #      GraphWeaver.register_enum("Species", PetKind)
    #
    # The mapping is inferred by name ("CAT" <-> PetKind::Cat); map: pins
    # renames, fallback: absorbs unknown wire values on cast (inputs stay
    # strict), requires: names files the generated code should require.
    # Generation fails naming any schema value that doesn't resolve —
    # exhaustiveness checked ahead of runtime.
    def register_enum(graphql_name, type, positional_map = nil, map: nil, fallback: nil, requires: nil)
      Codegen.register_enum(graphql_name, type, positional_map, map:, fallback:, requires:)
    end

    # Include app-owned helper modules into every struct generated from a
    # GraphQL type — derived values live as methods next to the honest wire
    # data, on the struct at runtime (fakes/cassettes included):
    #
    #      GraphWeaver.extend_type("Pet", PetHelpers)
    #
    # A helper that reads a wire field is checked by srb tc in the module's
    # own scope, not the struct's, so the field won't resolve — write it
    # # typed: false or reach it via T.unsafe(self). Or build the mixin inline
    # with a block (module_eval'd into an auto-named module — invisible to srb):
    #
    #      GraphWeaver.extend_type("Pet") do
    #        def display_name = "#{name} the pet"
    #      end
    #
    # Additive — repeated registrations stack.
    def extend_type(graphql_name, *mixins, requires: nil, **kw, &block)
      Codegen.extend_type(graphql_name, *mixins, requires:, **kw, &block)
    end

    # Restore the built-in scalars, dropping every custom registration —
    # the clean slate to reach for between tests or to undo overrides.
    # (Coercible built-ins are auto_coerce's job, not a reset flavor.)
    def reset_scalars!
      Codegen.reset_scalars!
    end

    # Empty the scalar registry entirely, built-ins included (see
    # reset_scalars! to restore the defaults).
    def clear_scalars!
      Codegen.clear_scalars!
    end

    # Drop every register_enum mapping. (No clear_ twin: unlike scalars,
    # there are no built-in enums to restore.)
    def reset_enums!
      Codegen.reset_enums!
    end

    # Drop every extend_type registration — mixins, requires, alias: paths.
    # The block-built modules under GraphWeaver::TypeHelpers stay, since
    # generated files may still name them.
    def reset_type_helpers!
      Codegen.reset_type_helpers!
    end

    # Every registry back to its starting state: built-in scalars restored,
    # enum mappings and type helpers dropped — the clean slate between tests.
    def reset_registrations!
      Codegen.reset_registrations!
    end

    # Parse a query into a typed query module:
    #
    #      PersonQuery = GraphWeaver.parse(schema:, query: "queries/person.graphql")
    #
    # schema: is a graphql-ruby schema or a Client (its schema, and its
    # transport as the module's default). query is a .graphql/.gql path (module
    # name derived from the file name
    # and the operation — see #module_name) or a raw query string (name
    # derived from the operation name,
    # falling back to "Query" for anonymous operations — collisions are
    # impossible since each parse gets its own container). Pass name: to
    # override, client: to bake the module's default client/transport.
    def parse(schema:, query:, name: nil, client: nil, fragments: fragments_paths)
      client ||= schema.transport if schema.is_a?(Client)
      schema = schema_for(schema)
      path = query if query.end_with?(".graphql", ".gql")
      if path
        query = File.read(path)
        name ||= module_name(path, query)
      end
      query = Codegen.inline_fragments(query, Codegen.load_fragments(fragments), path)

      Codegen.parse(schema:, query:, module_name: name, client:)
    end

    # One-shot dynamic execution — a throwaway client, no build step:
    #
    #      GraphWeaver.execute(schema, "query($id: ID!) { ... }", id: "1")   # => Response
    #      GraphWeaver.execute!(url, "query { viewer { login } }")           # => Result (or raise)
    #
    # The first argument is a url or schema source, exactly as
    # GraphWeaver.new; this is Client#execute on a client you don't keep.
    # (A url source introspects the schema on every call — keep a client
    # for more than one query.) Variables are plain kwargs, as on a
    # generated module (nothing reserved). execute returns the
    # Response envelope, execute! the typed result, raising QueryError on
    # top-level errors.
    def execute(source, query, **variables)
      client = source.is_a?(Client) ? source : new(source)
      client.execute(query, **variables)
    end

    # execute + data! — the typed result, or a raised QueryError. See execute.
    def execute!(source, query, **variables)
      execute(source, query, **variables).data!
    end
  end
end
