require "graphql"
require "sorbet-runtime"

require_relative "graph_weaver/logging"
require_relative "graph_weaver/internal"
require_relative "graph_weaver/errors"
require_relative "graph_weaver/coerce"
require_relative "graph_weaver/hints"
require_relative "graph_weaver/input_struct"
require_relative "graph_weaver/query_module"
require_relative "graph_weaver/response"
require_relative "graph_weaver/inflect"
require_relative "graph_weaver/codegen"
require_relative "graph_weaver/client"
require_relative "graph_weaver/in_process"
require_relative "graph_weaver/transport/http"
require_relative "graph_weaver/retry"
require_relative "graph_weaver/schema_loader"
require_relative "graph_weaver/version"
require_relative "graph_weaver/railtie" if defined?(::Rails::Railtie)

# opt-in extras:
#      require "graph_weaver/transport/faraday"        # Faraday transport
module GraphWeaver
  # The line every generated file opens with (see Codegen::Emit) — the marker
  # that tells generate! which files in the output directory are its to prune.
  GENERATED_HEADER = "# Generated by GraphWeaver"

  # How far into a file to look for it: the header sits under the `typed:` and
  # `frozen_string_literal:` magic comments, never deeper.
  HEADER_SCAN_LINES = 10
  private_constant :GENERATED_HEADER, :HEADER_SCAN_LINES

  class << self
    # A client for one GraphQL server — transport, schema, and scoped
    # scalars in one object (see Client):
    #
    #      github = GraphWeaver.new("https://api.github.com/graphql", auth: token, cache: true)
    #      RepoQuery = github.parse("queries/repo.graphql")
    #
    # The first argument is a url or any schema source (a live schema
    # class, or a path/SDL/introspection dump).
    def new(source, **options, &middleware)
      Client.new(source, **options, &middleware)
    end

    # The app's default client — how generated modules find their server:
    #
    #      GraphWeaver.client = GraphWeaver.new(url, auth: token)
    #
    # Anything satisfying the execute contract — a Client, a schema class,
    # a transport, a fake (testing's graphql: tag swaps one in per
    # example). Generated modules resolve per call -> per module
    # (MyQuery.client=) -> baked constant -> here.
    attr_accessor :client

    # the default client, when one is required
    def client!
      # in a spec suite this is nearly always a forgotten tag, and "set
      # GraphWeaver.client=" is advice for the wrong file — graph_weaver/rspec
      # being loaded is what says which suggestion is the useful one
      @client or raise Error, "no client configured — " + if defined?(Testing::RSpecIntegration)
        "tag the example graphql: :fake (or :in_process / :router), or build one with graphql_fake"
      elsif defined?(::RSpec)
        # a graphql: tag without graph_weaver/rspec is silent, and lands here
        "set GraphWeaver.client= or pass a client; if you tagged this example graphql:, " \
          "require \"graph_weaver/rspec\" in your spec helper — the tag does nothing without it"
      else
        "set GraphWeaver.client= or pass a client"
      end
    end

    # Called by generated code — not semver'd for direct use.
    #
    # Cast a response's data, keeping the server's own errors on a failure.
    # The common cause of a cast failure is a field that came back null *with
    # a reason attached* — a permission rule, a partial outage — and raising
    # only Sorbet's nil complaint throws that reason away, leaving whoever is
    # on call with a type error and no explanation.
    sig do
      params(struct: T.untyped, data: T.untyped, errors: T::Array[GraphWeaver::GraphQLError])
        .returns(T.untyped)
    end
    def cast_data(struct, data, errors)
      struct.from_h(data)
    rescue GraphWeaver::TypeError => e
      raise if errors.empty?

      detail = e.message.delete_prefix("failed to cast response into #{struct}: ")
      raise GraphWeaver::TypeError.new(
        struct:,
        message: "#{detail} — the server also reported: #{errors.map(&:message).join("; ")}",
      )
    end

    # Called by generated code — not semver'd for direct use.
    #
    # Shape-check a raw response envelope, returning it. Generated
    # from_response is public API taking anything with #to_h, so a malformed
    # body has to brand rather than escape as a raw Sorbet TypeError from a sig
    # (which fires before the struct's own rescue can see it). Lives here rather
    # than unrolled into every generated module.
    def check_envelope!(raw, struct)
      raw = raw.to_h if !raw.is_a?(Hash) && raw.respond_to?(:to_h)
      unless raw.is_a?(Hash)
        raise GraphWeaver::TypeError.new(struct:, message: "response must be an object, got #{raw.class}")
      end

      %w[data extensions].each do |key|
        value = raw[key]
        next if value.nil? || value.is_a?(Hash)

        raise GraphWeaver::TypeError.new(struct:, message: "response #{key.inspect} must be an object, got #{value.class}")
      end

      errors = raw["errors"]
      unless errors.nil? || (errors.is_a?(Array) && errors.all?(Hash))
        raise GraphWeaver::TypeError.new(struct:, message: "response \"errors\" must be an array of objects")
      end

      # A response with neither key isn't a GraphQL response at all — a client
      # that returned nil, one keying the envelope by symbol, one that typo'd
      # "dat". Each otherwise passes as a success carrying no data.
      unless raw.key?("data") || raw.key?("errors")
        found = raw.empty? ? "it is empty" : "got #{raw.keys.first(5).map(&:inspect).join(", ")}"
        raise GraphWeaver::TypeError.new(struct:, message:
          "response carried neither \"data\" nor \"errors\" — #{found}; " \
          "the keys are the wire's own, as strings")
      end

      raw
    end

    # What every relative path setting below is relative to: Rails.root in a
    # Rails app, the working directory otherwise. So a dev server or an rspec
    # run started from a subdirectory reads the same files a rake task does.
    # An absolute setting is left alone.
    attr_writer :root

    def root = (@root || rails_root || Dir.pwd).to_s

    # Not memoized: Rails.root isn't set when the gem is required. const_get
    # rather than a bare Rails — sorbet can't resolve a constant the gem
    # doesn't depend on, and something else may be named Rails.
    def rails_root
      return unless Object.const_defined?(:Rails)

      rails = Object.const_get(:Rails)
      rails.root if rails.respond_to?(:root)
    end
    private :rails_root

    # Conventional locations. Every directory setting is a LIST,
    # factory_bot-style: extra locations (a test-only dir, an engine's) can be
    # appended and every reader walks them all. Entries may be glob patterns,
    # and the generated default already matches per-schema layouts
    # (app/graphql/github/generated). Assigning a String wraps it, so pointing
    # at one directory stays a one-liner:
    #
    #      GraphWeaver.queries_paths = "app/graphql/operations"
    #      GraphWeaver.generated_paths << "spec/graphql/generated"
    #
    # schema_path is the exception, and singular on purpose: one generate! run
    # reads ONE schema, so a second dump in a list is a file nothing would ever
    # read. A second schema is a second generate! (schema: names it).
    attr_writer :schema_path

    def queries_paths = @queries_paths ||= ["app/graphql/queries"]
    def generated_paths = @generated_paths ||= ["app/graphql/generated", "app/graphql/*/generated"]

    # Reusable named fragments, defined once and available to every query —
    # each query inlines only the ones it (transitively) spreads, so the sent
    # query stays self-contained.
    def fragments_paths = @fragments_paths ||= ["app/graphql/fragments"]

    # nil restores the default; a String is one entry, not a second spelling
    def queries_paths=(paths)
      @queries_paths = paths && Array(paths)
    end

    def generated_paths=(paths)
      @generated_paths = paths && Array(paths)
    end

    def fragments_paths=(paths)
      @fragments_paths = paths && Array(paths)
    end

    def schema_path = @schema_path || "app/graphql/schema.json"

    # Set by every graph_weaver rake task: those tasks WRITE the generated
    # files, so loading them first lets a stale one block its own repair.
    # None of them needs the modules loaded.
    attr_accessor :skip_generated_load

    # The name of the shared module — the types that live once per schema
    # (input types, enums, unions hoisted from shared fragments) and are
    # aliased into every query module that touches them. Constant, not derived
    # from where you put the files: set it globally, or pass types_module: per
    # generate!. A multi-schema layout names it in the same initializer that
    # sets its paths.
    attr_writer :types_module

    def types_module = @types_module || "GraphQLTypes"

    # Generate every query in a directory — .graphql/.gql, subdirectories
    # included — into checked-in Ruby files. Paths default to the conventions
    # above; schema: defaults to the dump at schema_path (any supported
    # extension), and also takes a Client (its schema — the console object,
    # no dump needed):
    #
    #      GraphWeaver.generate!   # queries_paths -> generated_paths.first
    #
    # person.graphql => person_query.rb defining PersonQuery. Returns every
    # path the plan produces; a file already byte-identical is left untouched
    # (see #changed_files). Generated files the plan no longer produces are deleted
    # (see #orphaned), so renaming or dropping a .graphql leaves nothing
    # behind. Pair with a freshness spec (docs/generated_modules.md).
    def generate!(schema: nil, queries: queries_paths, output: generated_paths.first, client: nil,
      types_module: nil)
      schema = schema ? schema_for(schema) : locate_schema!

      if Internal::Util.query_files(queries).empty?
        # a brand-new app legitimately has none; a mistyped queries_paths looks
        # exactly the same, and prints nothing either way
        Internal::Log.log(:warn) { "no query documents under #{Array(queries).join(", ")} — nothing to generate" }
      end

      plan = generation_plan(queries:, schema:, client:, types_module:)
      @unmatched_registrations = Codegen.unmatched_registrations(schema)
      @changed_files = []
      written = plan.map do |filename, source|
        target = File.join(Internal::Util.resolve(output), filename)
        next target if current?(target, source)

        FileUtils.mkdir_p(File.dirname(target))
        # a rake task beside a watching dev server writes the same file: a
        # truncating write can leave a prefix that no longer parses, and it is
        # the running app that requires it next
        Internal::Util.atomic_write(target, source)
        reported = Internal::Util.relative(target)
        @changed_files << reported
        Internal::Log.log(:info) { "generated #{reported}" }
        target
      end

      orphaned(output, written).each do |orphan|
        File.delete(orphan)
        Internal::Log.log(:info) { "pruned #{Internal::Util.relative(orphan)}" }
      end

      written.map { |target| Internal::Util.relative(target) }
    end

    # Which of those files the last generate! actually wrote — the rest were
    # already byte-identical, so a run that changed one query touches one file
    # and a watching dev server has one module to reload.
    def changed_files = @changed_files || []

    # Generated files under output the current plan no longer produces — a
    # query renamed or deleted, a type dropped from the schema, a union no
    # longer hoisted. Left alone they'd keep being required by
    # load_generated!, resolving against a query that no longer exists.
    def orphaned(output, produced)
      generated_files(output) - produced
    end
    private :orphaned

    # Every .rb under output that GraphWeaver wrote, identified by the header
    # it emits. The header — not a *_query.rb glob — is what makes pruning
    # safe: this is a real directory, and a hand-written file in it must
    # survive regeneration.
    def generated_files(output)
      Dir[File.join(Internal::Util.resolve(output), "**/*.rb")].sort.select do |path|
        File.foreach(path).first(HEADER_SCAN_LINES).any? { |line| line.start_with?(GENERATED_HEADER) }
      end
    end
    private :generated_files

    # The freshness guard: raise unless every generated file matches what
    # the current schema + queries + scalar registrations would produce —
    # counting a generated file the plan no longer produces as stale, so a
    # deleted query can't leave a live module behind. One line in a spec, or
    # `rake graph_weaver:verify` in CI:
    #
    #      it "generated queries are current" do
    #        GraphWeaver.verify_generated!
    #      end
    def verify_generated!(schema: nil, queries: queries_paths, output: generated_paths.first, client: nil,
      types_module: nil)
      if Internal::Util.query_files(queries).empty?
        # green over nothing is worse than red: a CI gate stays passing
        # forever because someone typed app/graphql/querys
        raise Error, "no query documents under #{Array(queries).join(", ")} — this checked nothing, " \
          "so it proved nothing (set GraphWeaver.queries_paths, or pass queries:)"
      end

      schema = schema ? schema_for(schema) : locate_schema!
      plan = generation_plan(queries:, schema:, client:, types_module:)
      @unmatched_registrations = Codegen.unmatched_registrations(schema)
      stale = plan.filter_map do |filename, source|
        target = File.join(Internal::Util.resolve(output), filename)
        target unless current?(target, source)
      end
      # strays: a generated file the current schema + queries no longer produce
      stale += orphaned(output, plan.map { |filename, _| File.join(Internal::Util.resolve(output), filename) })

      unless stale.empty?
        raise Error, "stale generated queries — regenerate (rake graph_weaver:generate): " \
          "#{stale.map { |path| Internal::Util.relative(path) }.join(", ")}"
      end

      true
    end

    # Whether the file on disk is already what the plan would write — asked
    # before writing it, and before calling it stale. autocrlf rewrites line
    # endings on checkout, and a Windows working copy is neither stale
    # generated code nor a file worth rewriting.
    def current?(target, source)
      File.exist?(target) && File.read(target).gsub("\r\n", "\n") == source.gsub("\r\n", "\n")
    end
    private :current?

    # What the last generate!/verify_generated! couldn't match in the schema it
    # ran against — one sentence per registration, empty after a clean run. The
    # same list codegen logs at warn, kept here so the build can print it once
    # instead of once per query file.
    def unmatched_registrations = @unmatched_registrations || []

    # Which checked-in queries no longer validate — breaking-change
    # detection scoped to the operations you actually ship. Reports rather
    # than raising, keyed by file, JSON-ready like every #to_h here:
    #
    #      GraphWeaver.check_queries
    #      # => { "app/graphql/queries/person.graphql" =>
    #      #      [{ "message" => "Field 'titel' doesn't exist on type 'Person'",
    #      #         "line" => 4, "column" => 5 }] }
    #
    # Empty means every query validates. schema: defaults to the server as
    # it is now — a FRESH introspection of the url the dump records, or the
    # live schema class when the app default runs in-process — and the dump
    # is left alone; pass schema: and nothing touches the network.
    #
    # When that dump is a composed supergraph, an error naming a type is
    # branded with the subgraphs behind it — "…on type 'Product'
    # (products, reviews)", plus a "subgraphs" key — since knowing whose
    # code to look at is half the answer. A plain schema is unaffected.
    #
    # A different question from verify_generated!, which asks whether the
    # committed Ruby matches the committed schema. `rake
    # graph_weaver:queries:check` prints this and exits non-zero.
    def check_queries(schema: nil, queries: queries_paths, fragments: fragments_paths)
      # subgraph branding comes from the local supergraph dump, so a caller
      # supplying its own schema opts out of it
      table = schema ? nil : checked_routing_table
      schema = schema ? schema_for(schema) : refreshed_schema
      shared = Codegen.load_fragments(fragments)

      Internal::Util.query_files(queries).each_with_object({}) do |path, failures|
        errors = validation_errors(schema, File.read(path), shared, table)
        failures[Internal::Util.relative(path)] = errors if errors.any?
      end
    end

    # The routing table behind the schema check_queries is about to use,
    # when there is one: a composed supergraph dump says who resolves what,
    # so a validation error can name the subgraph whose code to look at. nil
    # for every other source — a plain schema is entirely unaffected — and
    # nil when a live schema class is what gets checked, since the dump then
    # isn't what the errors came from.
    def checked_routing_table
      return if Internal::Util.live_schema

      path = SchemaLoader.locate_path
      return unless path&.end_with?(".graphql", ".gql")

      sdl = File.read(path)
      SchemaLoader.routing_table(sdl) if SchemaLoader.federation_sdl?(sdl)
    end
    private :checked_routing_table

    # The schema check_queries defaults to: the server as it is now. Over a
    # socket that's a fresh introspection of the url the local dump recorded,
    # so no refresh step (and no rewritten dump) is needed first. In-process
    # it's the live schema class — for an app that IS the server, a dump is a
    # snapshot of its own code, and checking against it reports phantom
    # errors about a field you just added. Dumps with no url and no live
    # class — hand-written SDL, a composed supergraph — have nothing to
    # re-read, so they're checked as they are.
    def refreshed_schema
      live = Internal::Util.live_schema
      return live if live

      # locate_schema! raises the conventional "no schema dump" message
      path = SchemaLoader.locate_path or locate_schema!
      return SchemaLoader.load(path) unless SchemaLoader.provenance(path)&.key?("url")

      # source_transport rather than one built here: it reads the auth ENV var
      # the dump named, so `--auth MY_TOKEN` reaches this path too
      SchemaLoader.introspect(SchemaLoader.source_transport(path))
    end
    private :refreshed_schema

    # One query's schema-validation errors as JSON-ready hashes, with the
    # source position graphql-ruby reports. Unparseable counts as an error
    # too — it doesn't validate either, and inline_fragments (which parses
    # first) has already branded it with its position.
    def validation_errors(schema, source, shared, table = nil)
      # path omitted: the caller keys the report by file, so branding the
      # message with it too would just print the path twice
      schema.validate(Codegen.inline_fragments(source, shared)).map do |error|
        detail = error.to_h
        location = detail["locations"]&.first || {}
        subgraphs = table ? attribute(table, detail["extensions"]) : []
        entry = {
          "message" => subgraphs.empty? ? error.message : "#{error.message} (#{subgraphs.join(", ")})",
          "line" => location["line"],
          "column" => location["column"],
        }
        subgraphs.empty? ? entry : entry.merge("subgraphs" => subgraphs)
      end
    rescue GraphWeaver::ValidationError => e
      # an unparseable query: codegen folds the position (and the file) into
      # the message, and this report keeps them separate — same splitter the
      # rendered error uses, so the two can't drift apart
      e.errors.map do |detail|
        _path, _position, message = ValidationError.split(detail)
        detail.transform_keys(&:to_s).merge("message" => message)
      end
    end
    private :validation_errors

    # Which subgraphs a validation error is about, on a federated schema:
    # "Field 'weight' doesn't exist on type 'Product'" is much less useful
    # than the same line plus "(products)" — whose code to look at, whose
    # team to talk to. graphql-ruby reports the coordinate structurally, so
    # this is a lookup rather than message parsing. Both halves of the
    # coordinate are required: an argument error reports typeName "Field"
    # (the AST node kind, not a type), and looking that up would attribute
    # confidently and wrongly.
    def attribute(table, extensions)
      return [] unless extensions

      type_name, field_name = extensions.values_at("typeName", "fieldName")
      return [] unless type_name && field_name

      table.responsible(type_name, field_name)
    end
    private :attribute

    # Load the generated modules — one line in an initializer or spec
    # helper (loading happens only when you call this; skip it and
    # require files yourself if you'd rather):
    #
    #      GraphWeaver.load_generated!
    #
    # In Rails, prefer this over autoloading: Zeitwerk would expect
    # Generated::PersonQuery from generated/person_query.rb, and
    # generated code only changes on regeneration anyway (restart, like
    # a schema migration).
    def load_generated!(path = nil)
      paths = path ? [path] : generated_paths
      files = paths.flat_map { |dir| Dir[File.join(Internal::Util.resolve(dir), "**/*.rb")].sort }.uniq
      files.each do |file|
        require file
      rescue NameError => e
        reported = Internal::Util.relative(file)
        # a dropped extend_type leaves this include dangling; say so here,
        # because the raw NameError points at generated code and names no fix
        helper = e.message[/GraphWeaver::TypeHelpers::(\w+)/, 1]
        if helper
          raise Error, "#{reported} includes GraphWeaver::TypeHelpers::#{helper}, but nothing registers it — " \
            "the extend_type(#{helper.inspect}) it was generated from is gone. Re-add that registration, " \
            "or regenerate without it: rake graph_weaver:generate"
        end

        # an app's own mixin or enum class named by extend_type/register_enum
        raise Error, "#{reported} can't load: #{e.message}. It was generated with an extend_type or " \
          "register_enum whose constant is gone — re-add it, or regenerate: rake graph_weaver:generate"
      end
      Internal::Log.log(:info) do
        "loaded #{files.size} generated module(s) from #{paths.map { |dir| Internal::Util.relative(dir) }.join(", ")}"
      end
      files.map { |file| Internal::Util.relative(file) }
    end

    # Load the generated modules again after generate! rewrote them in a
    # running process — the second half of watch mode (see the Railtie), and
    # what a console needs after regenerating in another terminal:
    #
    #      GraphWeaver.reload_generated!
    #
    # `require` no-ops on a file it has already seen, and re-running one whose
    # constants still exist raises (a T::Enum refuses a second definition), so
    # the constants generation owns go first. Same caveat as load_queries!: an
    # object built from the previous module stays an instance of it. A module
    # whose query was just deleted keeps its old constant until restart —
    # nothing on disk says what it was called any more.
    def reload_generated!
      names = Internal::Util.query_files.map { |path| Internal::Util.module_name(path, File.read(path)) } << types_module
      names.each { |name| undefine(name) }

      generated_paths.each do |dir|
        Dir[File.join(Internal::Util.resolve(dir), "**/*.rb")].each do |file|
          # require stores the realpath; the path load_generated! passed is
          # the other one under a symlinked checkout
          $LOADED_FEATURES.delete(file)
          $LOADED_FEATURES.delete(File.realpath(file))
        end
      end
      load_generated!
    end

    # remove_const takes a bare name, and types_module may be namespaced
    def undefine(name)
      *outer, base = name.split("::")
      owner = outer.reduce(Object) do |mod, part|
        return unless mod.const_defined?(part, false)

        mod.const_get(part, false)
      end
      owner.send(:remove_const, base) if owner.const_defined?(base, false)
    end
    private :undefine

    # Anywhere GraphWeaver takes schema:, a Client stands for its schema — so
    # the console object and the rake task point at the same thing. A path
    # (String or Pathname) or SDL loads like it does everywhere else in the
    # library; without that it reached `schema.validate` as itself and failed
    # as `undefined method 'validate' for an instance of String`.
    def schema_for(source)
      return source.schema if source.is_a?(Client)
      return SchemaLoader.load(source) if source.is_a?(String) || source.respond_to?(:to_path)

      source
    end
    private :schema_for

    # the conventional schema dump, required
    def locate_schema!
      SchemaLoader.locate or raise Error,
        "no schema dump at #{schema_path} (.json/.graphql/.gql) — pass schema:, or cache one: GraphWeaver.new(url, cache: true).schema"
    end
    private :locate_schema!

    # (filename, source) per artifact. Types a schema shares across queries —
    # input types, schema enums, and each named shared fragment spread as a
    # whole-union field — are emitted once into the shared module, with query
    # modules aliasing what they use. That's the difference between hundreds of
    # duplicated bool_exp structs (or one Ruby class per query for the same
    # schema enum) and one copy per schema. (Single-query parse inlines
    # everything — there's no cross-query set to share against.)
    def generation_plan(queries:, schema:, client:, types_module: nil, fragments: fragments_paths)
      types_module ||= self.types_module
      used = { inputs: [], enums: [], mapped: [] }
      used_unions = []
      shared = Codegen.load_fragments(fragments)

      seen = {} # module name => the file that produced it, for the collision message

      plan = Internal::Util.query_files(queries).map do |path|
        source = File.read(path)
        name, filename = Internal::Util.generated_names(path, source)
        if (earlier = seen[name])
          raise Error, "duplicate query module #{name} — #{Internal::Util.relative(earlier)} and " \
            "#{Internal::Util.relative(path)} both generate it; " \
            "the module name comes from the file name alone (directories don't namespace it), so rename one"
        end
        seen[name] = path

        codegen = Codegen.new(
          schema:,
          query: Codegen.inline_fragments(source, shared, path),
          name:,
          client:,
          types_namespace: types_module,
          hoistable_unions: Codegen.shared_fragment_spreads(source, shared, path),
          path:,
        )
        out = codegen.generate
        codegen.variable_type_names.each { |kind, names| used[kind] |= names }
        used_unions |= codegen.used_union_names
        [filename, out]
      end

      if used_unions.any? || used.values.any?(&:any?)
        codegen = Codegen.new(schema:, query: "", name: types_module)
        plan = codegen.generate_types(
          inputs: used[:inputs], enums: used[:enums] + used[:mapped],
          unions: used_unions, fragments: shared,
        ).to_a + plan
      end

      plan
    end
    private :generation_plan

    # Whether generated modules/structs emit `extend T::Sig` (so `sig`
    # resolves standalone). Default (nil) auto-detects: an app that globally
    # injects T::Sig (`class Module; include T::Sig`) makes the per-struct
    # extend redundant — rubocop's Sorbet/RedundantExtendTSig flags it — so
    # generation skips it. Force with true/false. Resolved at generation time.
    #
    #      GraphWeaver.extend_t_sig = false   # never emit (rely on a global include)
    attr_writer :extend_t_sig

    # The resolved boolean codegen uses: the explicit setting, else emit
    # unless T::Sig is globally injected into Module.
    def extend_t_sig?
      @extend_t_sig.nil? ? !global_tsig? : @extend_t_sig
    end

    # Whether the host app has globally injected T::Sig into every module
    # (`class Module; include T::Sig`) — extracted so it's stubbable in tests.
    def global_tsig? = Module.include?(T::Sig)
    private :global_tsig?

    # Teach the generator how a GraphQL custom scalar deserializes into a
    # rich Ruby object (and serializes back onto the wire when used as a
    # variable):
    #
    #      GraphWeaver.register_scalar("Money", Money, requires: "bigdecimal")
    #
    # A field typed `Money` then generates `const :price, T.nilable(Money)`
    # and casts with `Money.parse(...)` in from_h. Pass a real class as
    # type: and cast:/serialize: are inferred from it — .parse/#to_s, or
    # .load/.dump — by probing the deserialize side (see ScalarType::CODECS).
    # Override with a Symbol method name (safest — no string to misspell), a
    # Proc(expr) => code string, or :itself to force pass-through. requires:
    # (a String or Array) names files the generated code needs — validated,
    # and actually required to confirm it resolves when type: is a real class.
    # cast: is also what an untyped variable input coerces through, so a
    # variable of this scalar takes the value OR its raw input ("12.00") with
    # no static loosening — see GraphWeaver::Coerce. Built-in scalars are
    # pre-registered the same way, so this also overrides them.
    #
    # fake: is the wire value the testing harness fabricates for this scalar
    # — a literal, or a proc handed the seeded Random so `rspec --seed` still
    # reproduces. Needed only when type: is a class the harness can't invent
    # a value for (your own Money, not Time/Integer/String), and it refuses
    # at fabrication time rather than feeding your cast a placeholder:
    #
    #      GraphWeaver.register_scalar("Money", Money, fake: "12.00")
    #
    # Pass a `Type.field` coordinate instead of a scalar name to override just
    # that one field — so the same scalar can deserialize as different Ruby
    # types across fields (a `Date` for `User.birthday`, a `Time` elsewhere):
    #
    #      GraphWeaver.register_scalar("User.birthday", Date)
    #
    # A field-level override wins over the scalar-name registration. Same
    # signature either way. Call before generating.
    def register_scalar(graphql_name, type, cast: nil, serialize: nil, requires: nil, fake: nil)
      Codegen.register_scalar(graphql_name, type, cast:, serialize:, requires:, fake:)
    end

    # Map a GraphQL enum onto an app-owned T::Enum, so generated code
    # speaks YOUR enum — casting wire values in, serializing members out:
    #
    #      GraphWeaver.register_enum("Species", PetKind)
    #
    # The mapping is inferred by name ("CAT" <-> PetKind::Cat); map: pins
    # renames, fallback: absorbs unknown wire values on cast (inputs stay
    # strict), requires: names files the generated code should require.
    # Generation fails naming any schema value that doesn't resolve —
    # exhaustiveness checked ahead of runtime.
    def register_enum(graphql_name, type, positional_map = nil, map: nil, fallback: nil, requires: nil)
      Codegen.register_enum(graphql_name, type, positional_map, map:, fallback:, requires:)
    end

    # Include app-owned helper modules into every struct generated from a
    # GraphQL type — derived values live as methods next to the honest wire
    # data, on the struct at runtime (fakes/cassettes included):
    #
    #      GraphWeaver.extend_type("Pet", PetHelpers)
    #
    # A helper that reads a wire field is checked by srb tc in the module's
    # own scope, not the struct's, so the field won't resolve — write it
    # # typed: false or reach it via T.unsafe(self). Or build the mixin inline
    # with a block (module_eval'd into an auto-named module — invisible to srb):
    #
    #      GraphWeaver.extend_type("Pet") do
    #        def display_name = "#{name} the pet"
    #      end
    #
    # Additive — repeated registrations stack.
    def extend_type(graphql_name, *mixins, requires: nil, **kw, &block)
      Codegen.extend_type(graphql_name, *mixins, requires:, **kw, &block)
    end

    # Every registry back to its starting state: built-in scalars restored,
    # enum mappings and type helpers dropped — the clean slate between tests,
    # or between generations for different schemas. (One registry at a time
    # is a Codegen call:
    # GraphWeaver::Codegen.reset_enums!, .reset_scalars!, .clear_scalars!,
    # .reset_type_helpers!)
    def reset_registrations!
      Codegen.reset_registrations!
    end

    # Parse a query into a typed query module:
    #
    #      PersonQuery = GraphWeaver.parse(schema:, query: "queries/person.graphql")
    #
    # schema: is a graphql-ruby schema or a Client (its schema, and its
    # transport as the module's default). query is a .graphql/.gql path (module
    # name derived from the file name and the operation — see #module_name) or
    # a raw query string (name derived from the operation name, falling back to
    # "Query" for anonymous operations — collisions are impossible since each
    # parse gets its own container). Pass name: to override, client: to bake
    # the module's default client/transport.
    def parse(schema:, query:, name: nil, client: nil, fragments: fragments_paths)
      client ||= schema if schema.is_a?(Client)
      schema = schema_for(schema)
      # Rails.root.join(...) hands you a Pathname, and to_path is the
      # ecosystem's "I am a path" — the same conversion schema: gets through
      # SchemaLoader.load. Without it end_with? below is a NoMethodError.
      query = query.to_path if query.respond_to?(:to_path)
      path = query if query.end_with?(".graphql", ".gql")
      if path
        query = File.read(Internal::Util.resolve(path))
        name ||= Internal::Util.module_name(path, query)
      elsif !query.include?("{")
        # every document has a selection set, so this is a path we won't read
        # — and it would otherwise fail as a syntax error about SCHEMA/SCALAR
        raise Error, "#{query.inspect} is not a GraphQL document — a query file must be named .graphql or .gql"
      end
      query = Codegen.inline_fragments(query, Codegen.load_fragments(fragments), path)

      Codegen.parse(schema:, query:, name:, client:, path:)
    end

    # One-shot dynamic execution — a throwaway client, no build step:
    #
    #      GraphWeaver.run(schema, "query($id: ID!) { ... }", id: "1")   # => Response
    #      GraphWeaver.run!(url, "query { viewer { login } }")           # => Result (or raise)
    #
    # The first argument is a url or schema source, exactly as
    # GraphWeaver.new; this is Client#run on a client you don't keep.
    # (A url source introspects the schema on every call — keep a client
    # for more than one query.) Variables are plain kwargs, as on a
    # generated module (nothing reserved). run returns the Response
    # envelope, run! the typed result, raising QueryError on top-level
    # errors.
    def run(source, query, **variables)
      client = source.is_a?(Client) ? source : new(source)
      client.run(query, **variables)
    end

    # run + data! — the typed result, or a raised QueryError. See run.
    def run!(source, query, **variables)
      run(source, query, **variables).data!
    end
  end
end
