# typed: true
# frozen_string_literal: true

require "active_support/inflector"
require "graphql"
require "sorbet-runtime"

# Generates plain, statically-typecheckable Ruby from a GraphQL query +
# schema: nested T::Structs, from_h casting code, and a sig'd execute
# method. Unlike StructTypes (which builds classes at parse time, visible
# only at runtime), the output is source on disk — srb tc sees the exact
# result type of each query.
class StructCodegen
  # sorbet types for scalars
  SCALARS = {
    "ID" => "String",
    "String" => "String",
    "Int" => "Integer",
    "Float" => "Float",
    "Boolean" => "T::Boolean",
    "Date" => "Date",
  }.freeze

  # deserialization for scalars whose wire format differs from their Ruby
  # type; anything absent passes through untouched
  SCALAR_CASTS = {
    "Date" => ->(expr) { "Date.iso8601(#{expr})" },
  }.freeze

  class Scalar
    def initialize(name)
      @name = name
    end

    def bare_type
      SCALARS.fetch(@name, "T.untyped")
    end

    def prop_type
      "T.nilable(#{bare_type})"
    end

    def cast(expr, _depth)
      SCALAR_CASTS.fetch(@name) { return expr }.call(expr)
    end

    def identity?
      !SCALAR_CASTS.key?(@name)
    end

    def non_null? = false
    def object = nil
  end

  class NonNull
    def initialize(of)
      @of = of
    end

    def bare_type = @of.bare_type
    def prop_type = bare_type
    def cast(expr, depth) = @of.cast(expr, depth)
    def identity? = @of.identity?
    def non_null? = true
    def object = @of.object
  end

  class List
    def initialize(of)
      @of = of
    end

    def bare_type
      "T::Array[#{@of.prop_type}]"
    end

    def prop_type
      "T.nilable(#{bare_type})"
    end

    def cast(expr, depth)
      var = "v#{depth}"
      element = if @of.non_null? || @of.identity?
        @of.identity? ? var : @of.cast(var, depth + 1)
      else
        "#{var}&.then { |v#{depth + 1}| #{@of.cast("v#{depth + 1}", depth + 2)} }"
      end

      "#{expr}.map { |#{var}| #{element} }"
    end

    def identity? = @of.identity?
    def non_null? = false
    def object = @of.object
  end

  class ObjectNode
    Field = Struct.new(:prop, :key, :node)

    attr_reader :class_name, :fields

    def initialize(class_name)
      @class_name = class_name
      @fields = []
    end

    def bare_type = class_name

    def prop_type
      "T.nilable(#{bare_type})"
    end

    def cast(expr, depth)
      "#{class_name}.from_h(#{expr})"
    end

    def identity? = false
    def non_null? = false
    def object = self
  end

  def initialize(schema:, schema_const:, query:, module_name:)
    @schema = schema
    @schema_const = schema_const
    @query = query.strip
    @module_name = module_name
  end

  def generate
    errors = @schema.validate(@query)
    if errors.any?
      raise ArgumentError, "invalid query: #{errors.map(&:message).join("; ")}"
    end

    doc = GraphQL.parse(@query)
    operation = doc.definitions.grep(GraphQL::Language::Nodes::OperationDefinition).first
    unless operation&.operation_type == "query"
      raise ArgumentError, "expected a query operation"
    end

    root = object_node(@schema.query, operation.selections, "Result")

    out = []
    out << "# typed: strict"
    out << "# frozen_string_literal: true"
    out << ""
    out << "# Generated by StructCodegen — do not edit."
    out << ""
    out << "module #{@module_name}"
    out << "  extend T::Sig"
    out << ""
    out << "  QUERY = T.let(<<~'GRAPHQL', String)"
    @query.each_line { |line| out << "    #{line}".rstrip }
    out << "  GRAPHQL"
    out << ""
    emit_object(root, out, 1)
    out << ""
    out << "  sig { params(variables: T::Hash[String, T.untyped]).returns(Result) }"
    out << "  def self.execute(variables = {})"
    out << "    result = #{@schema_const}.execute(QUERY, variables: variables).to_h"
    out << "    if (errors = result[\"errors\"])"
    out << "      raise \"query failed: \#{errors.inspect}\""
    out << "    end"
    out << ""
    out << "    Result.from_h(result.fetch(\"data\"))"
    out << "  end"
    out << "end"

    out.join("\n") + "\n"
  end

  private

  def object_node(type, selections, class_name)
    node = ObjectNode.new(class_name)
    child_names = [class_name]

    # gather Field selections by result name (alias-aware), skipping the
    # __typename fields; fragments are out of scope for this spike
    gathered = {}
    selections.each do |selection|
      unless selection.is_a?(GraphQL::Language::Nodes::Field)
        raise NotImplementedError, "only plain field selections are supported: #{selection.class}"
      end
      next if selection.name.start_with?("__")

      (gathered[selection.alias || selection.name] ||= []) << selection
    end

    gathered.each do |key, nodes|
      field_type = @schema.get_field(type.graphql_name, nodes.first.name).type
      sub_selections = nodes.flat_map(&:selections)

      child = if (core = unwrap(field_type)).kind.name == "OBJECT"
        name = pick_name(core.graphql_name, key, child_names)
        type_ref(field_type) { object_node(core, sub_selections, name) }
      else
        type_ref(field_type) { Scalar.new(core.graphql_name) }
      end

      prop = ActiveSupport::Inflector.underscore(key)
      node.fields << ObjectNode::Field.new(prop, key, child)
    end

    node
  end

  # rebuild the NON_NULL/LIST wrappers around the core node
  def type_ref(type, &core)
    case type.kind.name
    when "NON_NULL"
      NonNull.new(type_ref(type.of_type, &core))
    when "LIST"
      List.new(type_ref(type.of_type, &core))
    when "OBJECT", "SCALAR"
      core.call
    else
      raise NotImplementedError, "unsupported kind: #{type.kind.name}"
    end
  end

  def unwrap(type)
    type = type.of_type while type.kind.name == "NON_NULL" || type.kind.name == "LIST"
    type
  end

  def pick_name(type_name, key, taken)
    candidate = type_name
    candidate = "#{ActiveSupport::Inflector.camelize(key)}#{type_name}" if taken.include?(candidate)
    raise NotImplementedError, "class name collision: #{candidate}" if taken.include?(candidate)

    taken << candidate
    candidate
  end

  def emit_object(node, out, indent)
    pad = "  " * indent

    out << "#{pad}class #{node.class_name} < T::Struct"
    out << "#{pad}  extend T::Sig"
    out << ""

    node.fields.filter_map { |field| field.node.object }.each do |child|
      emit_object(child, out, indent + 1)
      out << ""
    end

    node.fields.each do |field|
      out << "#{pad}  const :#{field.prop}, #{field.node.prop_type}"
    end

    out << ""
    out << "#{pad}  sig { params(data: T::Hash[String, T.untyped]).returns(#{node.class_name}) }"
    out << "#{pad}  def self.from_h(data)"
    out << "#{pad}    new("
    node.fields.each do |field|
      out << "#{pad}      #{field.prop}: #{field_cast(field)},"
    end
    out << "#{pad}    )"
    out << "#{pad}  end"
    out << "#{pad}end"
  end

  def field_cast(field)
    node = field.node

    if node.non_null?
      raw = "data.fetch(#{field.key.inspect})"
      node.identity? ? raw : node.cast(raw, 1)
    else
      raw = "data[#{field.key.inspect}]"
      node.identity? ? raw : "#{raw}&.then { |v1| #{node.cast("v1", 2)} }"
    end
  end
end
