# typed: false
# frozen_string_literal: true

require "open3"

# The checked-in example modules can't be regenerated by `bin/generate` —
# examples/github needs the network and a token — so nothing catches it
# drifting from the emitter. It did: a rename left run.rb calling a constant
# the generated file no longer defined, and the example broke for anyone who
# followed the documented regeneration step. This is the cheap half of that
# guard: the names have to line up, checked without loading or a network.
RSpec.describe "checked-in examples" do
  EXAMPLES = File.expand_path("../examples", __dir__)

  it "reference generated modules that exist" do
    defined_modules = Dir["#{EXAMPLES}/github/generated/*.rb"].flat_map do |path|
      File.read(path).scan(/^module ([A-Z]\w*)/).flatten
    end

    referenced = File.read("#{EXAMPLES}/github/run.rb").scan(/\b([A-Z]\w*(?:Query|Mutation))\b/).flatten.uniq

    expect(referenced).not_to be_empty # the scan itself should keep working
    expect(referenced - defined_modules).to be_empty
  end

  it "generate the module names the emitter would" do
    # a mutation lands in <name>_mutation.rb defining <Name>Mutation, a query
    # in <name>_query.rb — the naming rule generated code is referenced by
    Dir["#{EXAMPLES}/github/generated/*.rb"].each do |path|
      expected = GraphWeaver::Inflect.camelize(File.basename(path, ".rb"))
      expect(File.read(path)).to include("module #{expected}")
    end
  end

  # the tour in examples/README.md is only useful while its links resolve
  it "link only to example files that exist" do
    links = File.read("#{EXAMPLES}/README.md").scan(/\]\((?!https?:)([^)#]+)\)/).flatten.uniq

    expect(links).not_to be_empty
    expect(links.reject { |link| File.exist?(File.join(EXAMPLES, link)) }).to be_empty
  end

  # federation.rb is the one example that needs no network, so the guard can
  # be the real thing: run it. A subprocess, because it parses modules into
  # the top-level namespace.
  it "run the federation example end to end" do
    out, status = Open3.capture2e(RbConfig.ruby, "#{EXAMPLES}/federation.rb")

    expect(status).to be_success, out
    expect(out).to include("_entities") # it crossed a boundary
    expect(out).to include("refused")
  end
end
