# typed: ignore — exercises eval-defined constants
require "bigdecimal"
require "graph_weaver/testing"
require "rake"
require "stringio"
require "tmpdir"

# An app with more than one schema. The top-level settings are the one graph
# every single-schema app already has; GraphWeaver.graph declares the others,
# and every entry point walks the list.
describe "GraphWeaver.graph" do
  # a sibling schema that shares nothing with Demo but the shape of the problem
  BILLING_SDL = <<~SDL
    scalar Money
    type Invoice { id: ID!, total: Money! }
    type Query { invoice(id: ID!): Invoice }
  SDL

  around do |example|
    Dir.mktmpdir do |dir|
      @dir = dir
      example.run
    ensure
      GraphWeaver.reset_graphs!
      GraphWeaver::Codegen.reset_registrations!
    end
  end

  # where each graph's queries and output live under the tmpdir
  def write_query(graph, name, source)
    dir = File.join(@dir, graph.to_s, "queries")
    FileUtils.mkdir_p(dir)
    File.write(File.join(dir, "#{name}.graphql"), source)
    dir
  end

  def output(graph) = File.join(@dir, graph.to_s, "generated")

  # the task as rake runs it, stdout captured
  def run_task(name)
    previous, Rake.application = Rake.application, RakeHarness.application
    RakeHarness.application.tasks.each(&:reenable)
    out = StringIO.new
    $stdout = out
    RakeHarness.application["graph_weaver:#{name}"].invoke
    out.string
  ensure
    $stdout = STDOUT
    Rake.application = previous
  end

  def billing_schema = File.join(@dir, "billing.graphql").tap { |p| File.write(p, BILLING_SDL) }

  # the two graphs the rest of the examples share: same file name in both, so
  # only the namespaces keep them apart
  def two_graphs(namespaced: true)
    write_query(:pets, "person", "query { person(id: 1) { birthday pets { species } } }\n")
    write_query(:billing, "person", "query { invoice(id: 1) { id total } }\n")

    dir, billing = @dir, billing_schema
    GraphWeaver.graph :pets do
      schema Demo::Schema
      queries File.join(dir, "pets/queries")
      output File.join(dir, "pets/generated")
      client Demo::Schema
      namespace "Pets" if namespaced
    end
    GraphWeaver.graph :billing do
      schema billing
      queries File.join(dir, "billing/queries")
      output File.join(dir, "billing/generated")
      namespace "Billing" if namespaced
      register_scalar "Money", BigDecimal, requires: "bigdecimal"
    end
  end

  it "generates each graph into its own output, under its own namespace" do
    two_graphs
    GraphWeaver.generate!

    pets = File.read(File.join(output(:pets), "person_query.rb"))
    billing = File.read(File.join(output(:billing), "person_query.rb"))
    expect(pets).to include("module Pets::PersonQuery")
    expect(billing).to include("module Billing::PersonQuery")
    # the namespace carries the shared types module too — two schemas both
    # hoisting into ::GraphQLTypes is a guaranteed collision, not a chance one —
    # and inside one it is named Types, which is what types.rb spells
    expect(File.read(File.join(output(:pets), "types.rb"))).to include("module Pets::Types")
  end

  it "keeps a graph's registrations out of every other graph" do
    two_graphs
    GraphWeaver.generate!

    # billing's block registered Money; pets never saw it, and neither did the
    # default graph an initializer writes to
    expect(File.read(File.join(output(:billing), "person_query.rb"))).to include("BigDecimal")
    expect(GraphWeaver::Codegen.scalar_registry).not_to have_key("Money")
  end

  it "refuses two graphs whose files generate the same module, naming both" do
    two_graphs(namespaced: false)

    expect { GraphWeaver.generate! }.to raise_error(GraphWeaver::Error, /PersonQuery.*namespace:/m)
  end

  it "reports every graph's changed files and unmatched registrations in one run" do
    two_graphs
    dir, billing = @dir, billing_schema
    GraphWeaver.graph :extra do
      schema billing
      queries File.join(dir, "billing/queries")
      output File.join(dir, "extra/generated")
      namespace "Extra"
      register_scalar "Doubloon", String
    end
    GraphWeaver.generate!

    expect(GraphWeaver.changed_files.grep(/pets/)).not_to be_empty
    expect(GraphWeaver.changed_files.grep(/billing/)).not_to be_empty
    expect(GraphWeaver.unmatched_registrations.join("\n")).to include("Doubloon")
    # scoping is what makes that list short: Money matches the schema it was
    # registered against, so it isn't in it
    expect(GraphWeaver.unmatched_registrations.join("\n")).not_to include("Money")
  end

  it "names the stale graph when verify fails" do
    two_graphs
    GraphWeaver.generate!
    File.write(File.join(output(:billing), "person_query.rb"), "# Generated by GraphWeaver\n")

    expect { GraphWeaver.verify_generated! }.to raise_error(GraphWeaver::Error, /billing/)
  end

  it "checks every graph's queries against its own schema" do
    two_graphs
    write_query(:billing, "broken", "query { invoice(id: 1) { nope } }\n")

    failures = GraphWeaver.check_queries
    expect(failures.keys.grep(/broken/)).not_to be_empty
    # pets' query validates against Demo, not against billing
    expect(failures.keys.grep(/pets/)).to be_empty
  end

  it "loads every graph's generated modules" do
    two_graphs
    GraphWeaver.generate!

    expect(GraphWeaver.load_generated!.grep(/person_query/).size).to eq 2
    expect(defined?(Pets::PersonQuery)).to eq "constant"
    expect(defined?(Billing::PersonQuery)).to eq "constant"
  end

  # a module says which graph it belongs to and nothing about transport — the
  # graph is where the client lives, so renaming one regenerates nothing
  it "gives each graph's modules its own graph and no client of their own" do
    two_graphs
    GraphWeaver.generate!

    pets = File.read(File.join(output(:pets), "person_query.rb"))
    billing = File.read(File.join(output(:billing), "person_query.rb"))

    expect(pets).to include("GRAPH = T.let(:pets, Symbol)")
    expect(billing).to include("GRAPH = T.let(:billing, Symbol)")
    expect(pets).not_to include("Demo::Schema")
  end

  # the point of the move: each graph's modules reach that graph's client,
  # resolved when they execute rather than spelled into their source
  # namespaces of their own, and no enum to define twice — see the :fake
  # example below for why
  it "runs each graph's modules against that graph's own client" do
    write_query(:owned_pets, "contact", "query { person(id: 1) { name } }\n")
    write_query(:owned_billing, "statement", "query { invoice(id: 1) { id } }\n")
    invoices = Class.new do
      def execute(_query, **) = { "data" => { "invoice" => { "id" => "7" } } }
    end.new
    dir, billing = @dir, billing_schema
    GraphWeaver.graph :owned_pets do
      schema Demo::Schema
      client Demo::Schema
      queries File.join(dir, "owned_pets/queries")
      output File.join(dir, "owned_pets/generated")
      namespace "OwnedPets"
    end
    GraphWeaver.graph :owned_billing do
      schema billing
      client invoices
      queries File.join(dir, "owned_billing/queries")
      output File.join(dir, "owned_billing/generated")
      namespace "OwnedBilling"
    end
    GraphWeaver.generate!
    GraphWeaver.load_generated!

    # one graph names the demo schema, the other the fake above — neither
    # module says anything about either, and GraphWeaver.client is unset
    expect(OwnedPets::ContactQuery.execute!.person.name).to eq "Daniel"
    expect(OwnedBilling::StatementQuery.execute!.invoice.id).to eq "7"
  end

  # An app that is a pure client of two remote APIs owns no schema class, so
  # the only way a second graph's dump can exist is for something to fetch it
  # — and the installer is single-graph, URL= names one endpoint, and
  # real_world.md's recipe writes the conventional path. The graph already
  # knows both halves: the file it wants and the url its modules post to.
  describe "a graph naming a dump it hasn't got yet" do
    before { Object.const_set(:POKE_CLIENT, GraphWeaver.new("https://beta.pokeapi.co/graphql/v1beta")) }

    after { Object.send(:remove_const, :POKE_CLIENT) }

    def poke = GraphWeaver.graphs.first

    def declare!(path = File.join(@dir, "poke/schema.json"))
      GraphWeaver.graph(:poke) do
        schema path
        client "POKE_CLIENT"
      end
    end

    it "names the dump before the file exists, where dump_path waits for one" do
      declare!

      expect(poke.named_dump_path).to eq File.join(@dir, "poke/schema.json")
      expect(poke.dump_path).to be_nil
    end

    # A Client stands for its schema wherever schema: is taken, and one built
    # from a dump stands for the file too — so a supergraph handed to
    # GraphWeaver.new is as named as one handed to schema "supergraph.graphql".
    it "names the dump a client was built from" do
      path = billing_schema
      client = GraphWeaver.new(path)
      GraphWeaver.graph(:billing) { schema client }
      billing = GraphWeaver.graphs.first

      expect(billing.named_dump_path).to eq path
      expect(billing.dump_path).to eq path
    end

    # SDL and a schema class name no dump, so neither grows one
    it "names no dump for inline SDL or a live class" do
      GraphWeaver.graph(:billing) { schema BILLING_SDL }
      GraphWeaver.graph(:pets) { schema Demo::Schema }
      GraphWeaver.graph(:live) { schema GraphWeaver.new(Demo::Schema) }

      expect(GraphWeaver.graphs.map(&:named_dump_path)).to eq [nil, nil, nil]
    end

    it "sources the missing dump from the url its modules already post to" do
      declare!

      expect(poke.dump_source).to eq "https://beta.pokeapi.co/graphql/v1beta"
    end

    # the recorded url is a fact the file states about itself; the client is
    # only the answer while there is no file to ask
    it "prefers the dump's own recorded source once there is one" do
      FileUtils.mkdir_p(File.join(@dir, "poke"))
      File.write(File.join(@dir, "poke/schema.json"),
        JSON.generate("graph_weaver" => { "url" => "https://recorded.example/graphql" }))
      declare!

      expect(poke.dump_source).to eq "https://recorded.example/graphql"
    end

    it "refuses a client constant nothing defines, naming the dump it can't fill" do
      path = File.join(@dir, "poke/schema.json")
      GraphWeaver.graph(:poke) do
        schema path
        client "NO_SUCH_CLIENT"
      end

      expect { poke.dump_source }.to raise_error(GraphWeaver::Error,
        /the client in graph :poke names "NO_SUCH_CLIENT" and nothing defines that constant/m)
    end
  end

  # The docs promise an app "either has graphs or has settings, never a silent
  # third thing" — and declaring a graph left the default app/graphql/queries
  # read by nobody: generate skipped its files, verify was green about them,
  # queries:check said every query validated, and the modules generated from
  # them before the graph existed kept loading in production.
  describe "a directory no declared graph covers" do
    around do |example|
      GraphWeaver.root = @dir
      example.run
    ensure
      GraphWeaver.root = nil
    end

    def orphan!(name = "person.graphql", source = "query { person(id: 1) { nmae } }\n")
      dir = File.join(@dir, "app/graphql/queries")
      FileUtils.mkdir_p(dir)
      File.write(File.join(dir, name), source)
    end

    it "refuses at generation, naming the files and what each graph does cover" do
      two_graphs
      orphan!

      expect { GraphWeaver.generate! }.to raise_error(GraphWeaver::Error) { |error|
        expect(error.message).to include "app/graphql/queries/person.graphql"
        expect(error.message).to include "graph :pets", "graph :billing"
      }
    end

    # the sharp edge: the gates that read the file and report it fine
    it "refuses in verify and check_queries too, so neither is green about it" do
      two_graphs
      GraphWeaver.generate!
      orphan!

      expect { GraphWeaver.verify_generated! }.to raise_error(GraphWeaver::Error, /person\.graphql/)
      expect { GraphWeaver.check_queries }.to raise_error(GraphWeaver::Error, /person\.graphql/)
    end

    # a module generated before the graph was declared: no task regenerates it,
    # no task prunes it, and the railtie loads it every boot
    it "refuses generated output no graph writes" do
      two_graphs
      dir = File.join(@dir, "app/graphql/generated")
      FileUtils.mkdir_p(dir)
      File.write(File.join(dir, "person_query.rb"), "# Generated by GraphWeaver\nmodule PersonQuery; end\n")

      expect { GraphWeaver.generate! }
        .to raise_error(GraphWeaver::Error, %r{app/graphql/generated/person_query\.rb})
    end

    # app/graphql/*/generated is in generated_paths, so a graph's own output is
    # found by the sweep — and is not a stray, because that graph writes it
    it "counts a directory a graph does cover, however the glob spells it" do
      write_query(:pets, "person", "query { person(id: 1) { name } }\n")
      dir = @dir
      GraphWeaver.graph :pets do
        schema Demo::Schema
        queries File.join(dir, "pets/queries")
        output File.join(dir, "app/graphql/pets/generated")
      end

      expect { GraphWeaver.generate! }.not_to raise_error
      expect { GraphWeaver.generate! }.not_to raise_error
    end

    # an app that declared none has no third thing to have: the settings ARE
    # its graph, and everything under them is covered by definition
    it "says nothing to an app that declared no graph" do
      orphan!("valid.graphql", "query { person(id: 1) { name } }\n")
      GraphWeaver.schema_path = File.join(@dir, "schema.graphql")
      File.write(GraphWeaver.schema_path, Demo::Schema.to_definition)

      expect { GraphWeaver.generate! }.not_to raise_error
    ensure
      GraphWeaver.schema_path = nil
    end
  end

  # `rake -T` is baked before :environment, so the task list can't name the
  # graphs an initializer declared — this is the task that can.
  it "lists every graph, the client each one calls, and what rake generate covers" do
    two_graphs
    listed = run_task("graphs")
    expect(listed).to include("pets", "billing", "Pets", "Billing")
    # which server a graph talks to is the one thing this task didn't say, and
    # it is what an app checks when a graph's requests go somewhere surprising
    expect(listed).to include("client: Demo::Schema")

    expect(run_task("generate")).to match(/wrote.*pets.*\n(.*\n)*.*billing/)
  end

  # A fake fabricates a wire value from the scalar registrations — so with two
  # graphs it has to use the ones the module it is answering was generated
  # with, or it hands a generated cast a value that cast can't read.
  it "fabricates a scalar the way the graph that owns the schema reads it" do
    schema = GraphQL::Schema.from_definition(BILLING_SDL)
    dir, billing = @dir, schema
    GraphWeaver.graph :billing do
      schema billing
      queries File.join(dir, "billing/queries")
      output File.join(dir, "billing/generated")
      namespace "Billing"
      register_scalar "Money", Date
    end

    fake = GraphWeaver::Testing::FakeClient.new(schema:)
    total = fake.execute("query { invoice(id: 1) { total } }").dig("data", "invoice", "total")

    expect { Date.iso8601(total) }.not_to raise_error
  end

  # a top-level registration is the app's answer for that scalar, so a graph
  # reads them at generation: in Rails the graph and the registrations live in
  # two initializers, and alphabetical filename order can't be what decides
  it "takes the top-level registrations however late they are made" do
    GraphWeaver.register_scalar("Date", String, cast: :itself, serialize: :itself)
    two_graphs
    GraphWeaver.generate!
    expect(File.read(File.join(output(:pets), "person_query.rb"))).not_to include("Date.iso8601")

    GraphWeaver.reset_graphs!
    GraphWeaver::Codegen.reset_registrations!
    two_graphs
    GraphWeaver.register_scalar("Date", String, cast: :itself, serialize: :itself)
    GraphWeaver.generate!
    expect(File.read(File.join(output(:pets), "person_query.rb"))).not_to include("Date.iso8601")
  end

  # `graphql: :fake` derives one schema for the suite; with two graphs that
  # answer varies per example, and picking one would fake one schema's shapes
  # at the other's module
  it "refuses to guess which schema a bare fake means" do
    two_graphs

    expect { GraphWeaver::Testing.config.reference_schema! }
      .to raise_error(GraphWeaver::Error, /2 graphs.*graphql_fake\(schema:/m)
  end

  # …but a module says which graph it came from, so a mode has an answer per
  # module even where the suite has none — each stand-in built from that
  # module's own schema, and in place of the client baked into it.
  # namespaces of their own, and queries that hoist no shared types: these
  # modules are loaded for real, and a T::Enum another example already
  # defined refuses to be defined twice
  it "fakes each graph's modules against that graph's own schema" do
    GraphWeaver::Testing.reset!
    # email is resolved nowhere in Demo, so a value can only have come from a
    # fake — and this is the graph with `client: Demo::Schema` baked in
    write_query(:faked_pets, "contact", "query { person(id: 1) { email } }\n")
    write_query(:faked_billing, "statement", "query { invoice(id: 1) { id } }\n")
    dir, billing = @dir, billing_schema
    GraphWeaver.graph :faked_pets do
      schema Demo::Schema
      client Demo::Schema
      queries File.join(dir, "faked_pets/queries")
      output File.join(dir, "faked_pets/generated")
      namespace "FakedPets"
    end
    GraphWeaver.graph :faked_billing do
      schema billing
      queries File.join(dir, "faked_billing/queries")
      output File.join(dir, "faked_billing/generated")
      namespace "FakedBilling"
    end
    GraphWeaver.generate!
    GraphWeaver.load_generated!
    GraphWeaver::Internal::TestClients.install(:fake)

    expect(FakedPets::ContactQuery.execute!.person.email).to be_a String
    # invoice exists in billing's schema alone
    expect(FakedBilling::StatementQuery.execute!.invoice.id).to be_a String
  ensure
    GraphWeaver::Internal::TestClients.reset!
    GraphWeaver::Testing.reset!
  end

  # A graph's registrations decide the Ruby shape codegen emitted a cast for,
  # so a fake that fabricated with the DEFAULT registrations handed
  # `BigDecimal(...)` something it can't read. The graph is known here, so
  # the fake takes its registry rather than matching one back off the schema
  # — which a graph named by a file can't be matched by.
  it "fabricates a file-backed graph's scalar the way that graph casts it" do
    GraphWeaver::Testing.reset!
    write_query(:money, "statement", "query { invoice(id: 1) { id total } }\n")
    dir, billing = @dir, billing_schema
    GraphWeaver.graph :money do
      schema billing
      queries File.join(dir, "money/queries")
      output File.join(dir, "money/generated")
      namespace "Statements"
      register_scalar "Money", BigDecimal, requires: "bigdecimal"
    end
    GraphWeaver.generate!
    GraphWeaver.load_generated!
    # the app's single graph: what the rspec hook puts in the client slot
    GraphWeaver.client = GraphWeaver::Internal::TestClients.client_for(:fake)

    expect(Statements::StatementQuery.execute!.invoice.total).to be_a BigDecimal
  ensure
    GraphWeaver::Testing.reset!
  end

  # the same, one graph along: here the answer comes per module, off its
  # baked GRAPH, rather than from the app having only one
  it "fabricates each graph's scalars the way that graph casts them" do
    GraphWeaver::Testing.reset!
    write_query(:invoiced, "statement", "query { invoice(id: 1) { id total } }\n")
    dir, billing = @dir, billing_schema
    GraphWeaver.graph :pets do
      schema Demo::Schema
      queries File.join(dir, "pets/queries")
      output File.join(dir, "pets/generated")
      namespace "Pets"
    end
    GraphWeaver.graph :invoiced do
      schema billing
      queries File.join(dir, "invoiced/queries")
      output File.join(dir, "invoiced/generated")
      namespace "Invoiced"
      register_scalar "Money", BigDecimal, requires: "bigdecimal"
    end
    GraphWeaver.generate!
    GraphWeaver.load_generated!
    GraphWeaver::Internal::TestClients.install(:fake)

    expect(Invoiced::StatementQuery.execute!.invoice.total).to be_a BigDecimal
  ensure
    GraphWeaver::Internal::TestClients.reset!
    GraphWeaver::Testing.reset!
  end

  # a mode asks the graph what it runs against before it asks the app
  it "runs :in_process against the class a graph names, not the client's" do
    GraphWeaver.client = GraphWeaver::InProcess.new(RouterGraph::Reviews::Schema)
    GraphWeaver.graph(:pets) { schema Demo::Schema }

    expect(GraphWeaver::Testing.config.schema_class!(GraphWeaver.graphs.first)).to be Demo::Schema
  ensure
    GraphWeaver.client = nil
  end

  # a graph is told where ITS class is declared; the app-wide advice
  # (config.schema, graphql_in_process) can't name a second graph's
  it "names the graph, and where to declare its class, when it names a dump" do
    GraphWeaver.graph(:storefront) { schema RouterGraph::SUPERGRAPH }

    expect { GraphWeaver::Testing.config.schema_class!(GraphWeaver.graphs.first) }
      .to raise_error(GraphWeaver::Error,
        /graph :storefront names type information.*GraphWeaver\.graph\(:storefront/m)
  end

  # branding is read off the graph's own dump, so a graph that names a
  # supergraph keeps it — knowing whose code to look at is half the answer, and
  # it costs no network
  it "names the subgraphs behind a validation error in a federated graph" do
    FileUtils.mkdir_p(File.join(@dir, "fed"))
    File.write(File.join(@dir, "fed/federated.graphql"), "{ product(upc: \"1\") { colour } }\n")
    dir = @dir
    GraphWeaver.graph :storefront do
      schema RouterGraph::SUPERGRAPH
      queries File.join(dir, "fed")
      output File.join(dir, "fed/generated")
      namespace "Storefront"
    end

    errors = GraphWeaver.check_queries.fetch(File.join(@dir, "fed/federated.graphql"))
    expect(errors.first["subgraphs"]).to eq %w[products reviews]
  end

  # the report is keyed by file, and two graphs may legitimately share a
  # queries directory — the same operations against two subgraphs — so the
  # second graph's verdict must not replace the first's
  it "keeps both graphs' errors when they share a queries directory" do
    two_graphs
    write_query(:pets, "broken", "query { person(id: 1) { nope } }\n")
    dir = @dir
    GraphWeaver.graph :sibling do
      schema Demo::Schema
      queries File.join(dir, "pets/queries")
      output File.join(dir, "sibling/generated")
      namespace "Sibling"
    end

    errors = GraphWeaver.check_queries.fetch(File.join(@dir, "pets/queries/broken.graphql"))
    expect(errors.size).to eq 1 # both graphs say the same thing, said once
    expect(errors.first["message"]).to match(/nope/)
  end

  # a namespace keeps the CONSTANTS apart; the file is still named after the
  # query file, so a shared output: overwrites one module with the other
  it "refuses two graphs that write the same file, namespaces notwithstanding" do
    write_query(:pets, "person", "query { person(id: 1) { name } }\n")
    write_query(:billing, "person", "query { person(id: 1) { name } }\n")
    dir = @dir
    %i[pets billing].each do |graph|
      GraphWeaver.graph graph do
        schema Demo::Schema
        queries File.join(dir, "#{graph}/queries")
        output File.join(dir, "shared/generated")
        namespace graph.to_s.capitalize
      end
    end

    expect { GraphWeaver.generate! }
      .to raise_error(GraphWeaver::Error, /person_query\.rb.*own output:/m)
  end

  # the name is the identity, so a to_prepare block that re-runs on every dev
  # reload must not stack up copies — it did, and the next regeneration then
  # refused on a graph colliding with ITSELF, wedging the dev server
  it "replaces a graph declared again under the same name" do
    2.times { two_graphs }

    expect(GraphWeaver.graphs.map(&:name)).to eq %i[pets billing]
    expect { GraphWeaver.generate! }.not_to raise_error
  end

  # …and the identity is the name, not its spelling: `graph "billing"` used to
  # declare a second graph beside `graph :billing` and generate over its output
  it "treats a String name and a Symbol name as one graph" do
    GraphWeaver.graph("solo") { schema Demo::Schema }
    GraphWeaver.graph(:solo) { schema Demo::Schema }

    expect(GraphWeaver.graphs.map(&:name)).to eq [:solo]
  end

  # a parsed module generates no file, so under a test mode in a multi-graph
  # app it used to be a dead end: nothing said which graph it belonged to, and
  # the refusal advised regenerating, which cannot reach it
  describe "GraphWeaver.parse in a multi-graph app" do
    before do
      GraphWeaver.graph(:pets) { schema Demo::Schema }
      GraphWeaver.graph(:billing) { schema BILLING_SDL }
    end

    it "bakes the graph whose schema it was parsed against" do
      mod = GraphWeaver.parse(schema: Demo::Schema, query: "{ people { name } }")

      expect(mod.const_get(:GRAPH, false)).to eq :pets
    end

    it "takes graph: for a schema no graph runs in-process" do
      mod = GraphWeaver.parse(schema: Demo::Schema, query: "{ people { name } }", graph: "billing")

      expect(mod.const_get(:GRAPH, false)).to eq :billing
    end

    it "refuses a graph: that isn't declared, naming the ones that are" do
      expect { GraphWeaver.parse(schema: Demo::Schema, query: "{ people { name } }", graph: :nope) }
        .to raise_error(ArgumentError, "graph: :nope isn't declared — this app declares :pets, :billing")
    end
  end

  # the name is written into every module the graph generates, so it has to be
  # something generated source can spell
  it "refuses a name that isn't a Symbol or a String" do
    expect { GraphWeaver.graph(Demo::Schema) { schema Demo::Schema } }
      .to raise_error(ArgumentError, /Symbol or a String/)
  end

  # `schema: Accounts::Schema` can't be written at the top of a Rails
  # initializer — Zeitwerk is set up in a finisher, after initializers run — and
  # declaring from to_prepare is too late for watch mode to see the graph
  it "takes a callable schema, resolved when it is asked for" do
    write_query(:pets, "person", "query { person(id: 1) { name } }\n")
    resolved = 0
    dir = @dir
    GraphWeaver.graph :pets do
      schema -> { resolved += 1; Demo::Schema }
      queries File.join(dir, "pets/queries")
      output File.join(dir, "pets/generated")
      namespace "Pets"
    end

    expect(resolved).to be_zero # not at declaration
    GraphWeaver.generate!
    expect(resolved).to be_positive
    expect(File.read(File.join(output(:pets), "person_query.rb"))).to include("module Pets::PersonQuery")
  end

  # two schemas hoisting an enum into one GraphQLTypes is a certainty, not a
  # chance — and a T::Enum refuses a second definition, so without this the app
  # died at boot with sorbet-runtime's "already initialized", naming no graph
  it "refuses two graphs that hoist into the same shared types module" do
    write_query(:pets, "person", "query { person(id: 1) { pets { species } } }\n")
    write_query(:billing, "invoice", "query { person(id: 1) { pets { species } } }\n")
    dir = @dir
    %i[pets billing].each do |graph|
      GraphWeaver.graph graph do
        schema Demo::Schema
        queries File.join(dir, "#{graph}/queries")
        output File.join(dir, "#{graph}/generated")
      end
    end

    expect { GraphWeaver.generate! }
      .to raise_error(GraphWeaver::Error, /GraphQLTypes.*namespace:/m)
  end

  # watch mode regenerates on a request and keeps serving when a query doesn't
  # compile, which needs generation to be all-or-nothing — it was per graph,
  # so a refused run left the first graph rewritten and the second stale
  it "writes nothing when a later graph refuses" do
    two_graphs
    GraphWeaver.generate!
    before = Dir[File.join(output(:pets), "**/*.rb")].to_h { |path| [path, File.read(path)] }

    # a second pets query whose module collides with the first
    write_query(:pets, "person", "query { person(id: 1) { name } }\n")
    write_query(:billing, "person", "query { invoice(id: 1) { nope } }\n")

    expect { GraphWeaver.generate! }.to raise_error(GraphWeaver::Error)
    expect(Dir[File.join(output(:pets), "**/*.rb")].to_h { |path| [path, File.read(path)] }).to eq before
  end

  # "renaming or dropping a .graphql leaves nothing behind" — an empty types/
  # directory is something behind
  it "prunes a directory whose last generated file it removed" do
    two_graphs
    GraphWeaver.generate!
    expect(Dir).to exist File.join(output(:pets), "types")

    # the enum was the only thing being hoisted
    write_query(:pets, "person", "query { person(id: 1) { name } }\n")
    GraphWeaver.generate!

    expect(Dir).not_to exist File.join(output(:pets), "types")
    expect(Dir).to exist output(:pets)
  end

  # the default graph is the settings, so an app that never calls .graph is
  # exactly where it was
  it "leaves an app with no declared graph alone" do
    expect(GraphWeaver.graphs.size).to eq 1
    expect(GraphWeaver.graphs.first.registry).to be GraphWeaver::Codegen.registry
  end
end
