# typed: ignore — exercises eval-defined constants
require "bigdecimal"
require "graph_weaver/testing"
require "rake"
require "stringio"
require "tmpdir"

# An app with more than one schema. The top-level settings are the one graph
# every single-schema app already has; GraphWeaver.graph declares the others,
# and every entry point walks the list.
describe "GraphWeaver.graph" do
  # a sibling schema that shares nothing with Demo but the shape of the problem
  BILLING_SDL = <<~SDL
    scalar Money
    type Invoice { id: ID!, total: Money! }
    type Query { invoice(id: ID!): Invoice }
  SDL

  around do |example|
    Dir.mktmpdir do |dir|
      @dir = dir
      example.run
    ensure
      GraphWeaver.reset_graphs!
      GraphWeaver::Codegen.reset_registrations!
    end
  end

  # where each graph's queries and output live under the tmpdir
  def write_query(graph, name, source)
    dir = File.join(@dir, graph.to_s, "queries")
    FileUtils.mkdir_p(dir)
    File.write(File.join(dir, "#{name}.graphql"), source)
    dir
  end

  def output(graph) = File.join(@dir, graph.to_s, "generated")

  # the task as rake runs it, stdout captured
  def run_task(name)
    previous, Rake.application = Rake.application, RakeHarness.application
    RakeHarness.application.tasks.each(&:reenable)
    out = StringIO.new
    $stdout = out
    RakeHarness.application["graph_weaver:#{name}"].invoke
    out.string
  ensure
    $stdout = STDOUT
    Rake.application = previous
  end

  def billing_schema = File.join(@dir, "billing.graphql").tap { |p| File.write(p, BILLING_SDL) }

  # the two graphs the rest of the examples share: same file name in both, so
  # only the namespaces keep them apart
  def two_graphs(namespace: true)
    write_query(:pets, "person", "query { person(id: 1) { birthday pets { species } } }\n")
    write_query(:billing, "person", "query { invoice(id: 1) { id total } }\n")

    GraphWeaver.graph :pets,
      schema: Demo::Schema, queries: File.join(@dir, "pets/queries"), output: output(:pets),
      client: Demo::Schema, namespace: (namespace ? "Pets" : nil)
    GraphWeaver.graph :billing,
      schema: billing_schema, queries: File.join(@dir, "billing/queries"), output: output(:billing),
      namespace: (namespace ? "Billing" : nil) do
        register_scalar "Money", BigDecimal, requires: "bigdecimal"
      end
  end

  it "generates each graph into its own output, under its own namespace" do
    two_graphs
    GraphWeaver.generate!

    pets = File.read(File.join(output(:pets), "person_query.rb"))
    billing = File.read(File.join(output(:billing), "person_query.rb"))
    expect(pets).to include("module Pets::PersonQuery")
    expect(billing).to include("module Billing::PersonQuery")
    # the namespace carries the shared types module too — two schemas both
    # hoisting into ::GraphQLTypes is a guaranteed collision, not a chance one
    expect(File.read(File.join(output(:pets), "types.rb"))).to include("module Pets::GraphQLTypes")
  end

  it "keeps a graph's registrations out of every other graph" do
    two_graphs
    GraphWeaver.generate!

    # billing's block registered Money; pets never saw it, and neither did the
    # default graph an initializer writes to
    expect(File.read(File.join(output(:billing), "person_query.rb"))).to include("BigDecimal")
    expect(GraphWeaver::Codegen.scalar_registry).not_to have_key("Money")
  end

  it "refuses two graphs whose files generate the same module, naming both" do
    two_graphs(namespace: false)

    expect { GraphWeaver.generate! }.to raise_error(GraphWeaver::Error, /PersonQuery.*namespace:/m)
  end

  it "reports every graph's changed files and unmatched registrations in one run" do
    two_graphs
    GraphWeaver.graph :extra,
      schema: billing_schema, queries: File.join(@dir, "billing/queries"), output: output(:extra),
      namespace: "Extra" do
        register_scalar "Doubloon", String
      end
    GraphWeaver.generate!

    expect(GraphWeaver.changed_files.grep(/pets/)).not_to be_empty
    expect(GraphWeaver.changed_files.grep(/billing/)).not_to be_empty
    expect(GraphWeaver.unmatched_registrations.join("\n")).to include("Doubloon")
    # scoping is what makes that list short: Money matches the schema it was
    # registered against, so it isn't in it
    expect(GraphWeaver.unmatched_registrations.join("\n")).not_to include("Money")
  end

  it "names the stale graph when verify fails" do
    two_graphs
    GraphWeaver.generate!
    File.write(File.join(output(:billing), "person_query.rb"), "# Generated by GraphWeaver\n")

    expect { GraphWeaver.verify_generated! }.to raise_error(GraphWeaver::Error, /billing/)
  end

  it "checks every graph's queries against its own schema" do
    two_graphs
    write_query(:billing, "broken", "query { invoice(id: 1) { nope } }\n")

    failures = GraphWeaver.check_queries
    expect(failures.keys.grep(/broken/)).not_to be_empty
    # pets' query validates against Demo, not against billing
    expect(failures.keys.grep(/pets/)).to be_empty
  end

  it "loads every graph's generated modules" do
    two_graphs
    GraphWeaver.generate!

    expect(GraphWeaver.load_generated!.grep(/person_query/).size).to eq 2
    expect(defined?(Pets::PersonQuery)).to eq "constant"
    expect(defined?(Billing::PersonQuery)).to eq "constant"
  end

  it "bakes each graph's client into its own modules" do
    two_graphs
    GraphWeaver.generate!

    expect(File.read(File.join(output(:pets), "person_query.rb"))).to include("Demo::Schema")
    expect(File.read(File.join(output(:billing), "person_query.rb"))).not_to include("DEFAULT_CLIENT")
  end

  # `rake -T` is baked before :environment, so the task list can't name the
  # graphs an initializer declared — this is the task that can.
  it "lists every graph, and what rake generate covers" do
    two_graphs
    listed = run_task("graphs")
    expect(listed).to include("pets", "billing", "Pets", "Billing")

    expect(run_task("generate")).to match(/wrote.*pets.*\n(.*\n)*.*billing/)
  end

  # A fake fabricates a wire value from the scalar registrations — so with two
  # graphs it has to use the ones the module it is answering was generated
  # with, or it hands a generated cast a value that cast can't read.
  it "fabricates a scalar the way the graph that owns the schema reads it" do
    schema = GraphQL::Schema.from_definition(BILLING_SDL)
    GraphWeaver.graph :billing, schema:, queries: File.join(@dir, "billing/queries"),
      output: output(:billing), namespace: "Billing" do
        register_scalar "Money", Date
      end

    fake = GraphWeaver::Testing::FakeClient.new(schema:)
    total = fake.execute("query { invoice(id: 1) { total } }").dig("data", "invoice", "total")

    expect { Date.iso8601(total) }.not_to raise_error
  end

  # graphs are declared in one initializer and scalars registered in another,
  # so a graph that copied the top-level registrations when it was DECLARED
  # would depend on which of the two ran first
  it "takes the top-level registrations as they are when it generates" do
    two_graphs
    GraphWeaver.register_scalar("Date", String, cast: :itself, serialize: :itself)
    GraphWeaver.generate!

    expect(File.read(File.join(output(:pets), "person_query.rb"))).not_to include("Date.iso8601")
  end

  # `graphql: :fake` derives one schema for the suite; with two graphs that
  # answer varies per example, and picking one would fake one schema's shapes
  # at the other's module
  it "refuses to guess which schema a bare fake means" do
    two_graphs

    expect { GraphWeaver::Testing.config.reference_schema! }
      .to raise_error(GraphWeaver::Error, /2 graphs.*graphql_fake\(schema:/m)
  end

  # …but a module says which graph it came from, so a mode has an answer per
  # module even where the suite has none — each stand-in built from that
  # module's own schema, and in place of the client baked into it.
  # namespaces of their own, and queries that hoist no shared types: these
  # modules are loaded for real, and a T::Enum another example already
  # defined refuses to be defined twice
  it "fakes each graph's modules against that graph's own schema" do
    GraphWeaver::Testing.reset!
    # email is resolved nowhere in Demo, so a value can only have come from a
    # fake — and this is the graph with `client: Demo::Schema` baked in
    write_query(:faked_pets, "contact", "query { person(id: 1) { email } }\n")
    write_query(:faked_billing, "statement", "query { invoice(id: 1) { id } }\n")
    GraphWeaver.graph :faked_pets, schema: Demo::Schema, client: Demo::Schema,
      queries: File.join(@dir, "faked_pets/queries"), output: output(:faked_pets),
      namespace: "FakedPets"
    GraphWeaver.graph :faked_billing, schema: billing_schema,
      queries: File.join(@dir, "faked_billing/queries"), output: output(:faked_billing),
      namespace: "FakedBilling"
    GraphWeaver.generate!
    GraphWeaver.load_generated!
    GraphWeaver::Internal::TestClients.install(:fake)

    expect(FakedPets::ContactQuery.execute!.person.email).to be_a String
    # invoice exists in billing's schema alone
    expect(FakedBilling::StatementQuery.execute!.invoice.id).to be_a String
  ensure
    GraphWeaver::Internal::TestClients.reset!
    GraphWeaver::Testing.reset!
  end

  # A graph's registrations decide the Ruby shape codegen emitted a cast for,
  # so a fake that fabricated with the DEFAULT registrations handed
  # `BigDecimal(...)` something it can't read. The graph is known here, so
  # the fake takes its registry rather than matching one back off the schema
  # — which a graph named by a file can't be matched by.
  it "fabricates a file-backed graph's scalar the way that graph casts it" do
    GraphWeaver::Testing.reset!
    write_query(:money, "statement", "query { invoice(id: 1) { id total } }\n")
    GraphWeaver.graph :money, schema: billing_schema,
      queries: File.join(@dir, "money/queries"), output: output(:money),
      namespace: "Statements" do
        register_scalar "Money", BigDecimal, requires: "bigdecimal"
      end
    GraphWeaver.generate!
    GraphWeaver.load_generated!
    # the app's single graph: what the rspec hook puts in the client slot
    GraphWeaver.client = GraphWeaver::Internal::TestClients.client_for(:fake)

    expect(Statements::StatementQuery.execute!.invoice.total).to be_a BigDecimal
  ensure
    GraphWeaver::Testing.reset!
  end

  # the same, one graph along: here the answer comes per module, off its
  # baked GRAPH, rather than from the app having only one
  it "fabricates each graph's scalars the way that graph casts them" do
    GraphWeaver::Testing.reset!
    write_query(:invoiced, "statement", "query { invoice(id: 1) { id total } }\n")
    GraphWeaver.graph :pets, schema: Demo::Schema,
      queries: File.join(@dir, "pets/queries"), output: output(:pets), namespace: "Pets"
    GraphWeaver.graph :invoiced, schema: billing_schema,
      queries: File.join(@dir, "invoiced/queries"), output: output(:invoiced),
      namespace: "Invoiced" do
        register_scalar "Money", BigDecimal, requires: "bigdecimal"
      end
    GraphWeaver.generate!
    GraphWeaver.load_generated!
    GraphWeaver::Internal::TestClients.install(:fake)

    expect(Invoiced::StatementQuery.execute!.invoice.total).to be_a BigDecimal
  ensure
    GraphWeaver::Internal::TestClients.reset!
    GraphWeaver::Testing.reset!
  end

  # a mode asks the graph what it runs against before it asks the app
  it "runs :in_process against the class a graph names, not the client's" do
    GraphWeaver.client = GraphWeaver::InProcess.new(RouterGraph::Reviews::Schema)
    GraphWeaver.graph :pets, schema: Demo::Schema

    expect(GraphWeaver::Testing.config.schema_class!(GraphWeaver.graphs.first)).to be Demo::Schema
  ensure
    GraphWeaver.client = nil
  end

  # a graph is told where ITS class is declared; the app-wide advice
  # (config.schema, graphql_in_process) can't name a second graph's
  it "names the graph, and where to declare its class, when it names a dump" do
    GraphWeaver.graph :storefront, schema: RouterGraph::SUPERGRAPH

    expect { GraphWeaver::Testing.config.schema_class!(GraphWeaver.graphs.first) }
      .to raise_error(GraphWeaver::Error,
        /graph :storefront names type information.*GraphWeaver\.graph\(:storefront/m)
  end

  # branding is read off the graph's own dump, so a graph that names a
  # supergraph keeps it — knowing whose code to look at is half the answer, and
  # it costs no network
  it "names the subgraphs behind a validation error in a federated graph" do
    FileUtils.mkdir_p(File.join(@dir, "fed"))
    File.write(File.join(@dir, "fed/federated.graphql"), "{ product(upc: \"1\") { colour } }\n")
    GraphWeaver.graph :storefront, schema: RouterGraph::SUPERGRAPH,
      queries: File.join(@dir, "fed"), output: output(:fed), namespace: "Storefront"

    errors = GraphWeaver.check_queries.fetch(File.join(@dir, "fed/federated.graphql"))
    expect(errors.first["subgraphs"]).to eq %w[products reviews]
  end

  # the report is keyed by file, and two graphs may legitimately share a
  # queries directory — the same operations against two subgraphs — so the
  # second graph's verdict must not replace the first's
  it "keeps both graphs' errors when they share a queries directory" do
    two_graphs
    write_query(:pets, "broken", "query { person(id: 1) { nope } }\n")
    GraphWeaver.graph :sibling, schema: Demo::Schema, queries: File.join(@dir, "pets/queries"),
      output: output(:sibling), namespace: "Sibling"

    errors = GraphWeaver.check_queries.fetch(File.join(@dir, "pets/queries/broken.graphql"))
    expect(errors.size).to eq 1 # both graphs say the same thing, said once
    expect(errors.first["message"]).to match(/nope/)
  end

  # a namespace keeps the CONSTANTS apart; the file is still named after the
  # query file, so a shared output: overwrites one module with the other
  it "refuses two graphs that write the same file, namespaces notwithstanding" do
    write_query(:pets, "person", "query { person(id: 1) { name } }\n")
    write_query(:billing, "person", "query { person(id: 1) { name } }\n")
    %i[pets billing].each do |name|
      GraphWeaver.graph name, schema: Demo::Schema, queries: File.join(@dir, "#{name}/queries"),
        output: output(:shared), namespace: name.to_s.capitalize
    end

    expect { GraphWeaver.generate! }
      .to raise_error(GraphWeaver::Error, /person_query\.rb.*own output:/m)
  end

  # the name is the identity, so a to_prepare block that re-runs on every dev
  # reload must not stack up copies — it did, and the next regeneration then
  # refused on a graph colliding with ITSELF, wedging the dev server
  it "replaces a graph declared again under the same name" do
    2.times { two_graphs }

    expect(GraphWeaver.graphs.map(&:name)).to eq %i[pets billing]
    expect { GraphWeaver.generate! }.not_to raise_error
  end

  # the name is written into every module the graph generates, so it has to be
  # something generated source can spell
  it "refuses a name that isn't a Symbol or a String" do
    expect { GraphWeaver.graph(Demo::Schema, schema: Demo::Schema) }
      .to raise_error(ArgumentError, /Symbol or a String/)
  end

  # `schema: Accounts::Schema` can't be written at the top of a Rails
  # initializer — Zeitwerk is set up in a finisher, after initializers run — and
  # declaring from to_prepare is too late for watch mode to see the graph
  it "takes a callable schema, resolved when it is asked for" do
    write_query(:pets, "person", "query { person(id: 1) { name } }\n")
    resolved = 0
    GraphWeaver.graph :pets, schema: -> { resolved += 1; Demo::Schema },
      queries: File.join(@dir, "pets/queries"), output: output(:pets), namespace: "Pets"

    expect(resolved).to be_zero # not at declaration
    GraphWeaver.generate!
    expect(resolved).to be_positive
    expect(File.read(File.join(output(:pets), "person_query.rb"))).to include("module Pets::PersonQuery")
  end

  # two schemas hoisting an enum into one GraphQLTypes is a certainty, not a
  # chance — and a T::Enum refuses a second definition, so without this the app
  # died at boot with sorbet-runtime's "already initialized", naming no graph
  it "refuses two graphs that hoist into the same shared types module" do
    write_query(:pets, "person", "query { person(id: 1) { pets { species } } }\n")
    write_query(:billing, "invoice", "query { person(id: 1) { pets { species } } }\n")
    %i[pets billing].each do |name|
      GraphWeaver.graph name, schema: Demo::Schema,
        queries: File.join(@dir, "#{name}/queries"), output: output(name)
    end

    expect { GraphWeaver.generate! }
      .to raise_error(GraphWeaver::Error, /GraphQLTypes.*namespace:/m)
  end

  # watch mode regenerates on a request and keeps serving when a query doesn't
  # compile, which needs generation to be all-or-nothing — it was per graph,
  # so a refused run left the first graph rewritten and the second stale
  it "writes nothing when a later graph refuses" do
    two_graphs
    GraphWeaver.generate!
    before = Dir[File.join(output(:pets), "**/*.rb")].to_h { |path| [path, File.read(path)] }

    # a second pets query whose module collides with the first
    write_query(:pets, "person", "query { person(id: 1) { name } }\n")
    write_query(:billing, "person", "query { invoice(id: 1) { nope } }\n")

    expect { GraphWeaver.generate! }.to raise_error(GraphWeaver::Error)
    expect(Dir[File.join(output(:pets), "**/*.rb")].to_h { |path| [path, File.read(path)] }).to eq before
  end

  # "renaming or dropping a .graphql leaves nothing behind" — an empty types/
  # directory is something behind
  it "prunes a directory whose last generated file it removed" do
    two_graphs
    GraphWeaver.generate!
    expect(Dir).to exist File.join(output(:pets), "types")

    # the enum was the only thing being hoisted
    write_query(:pets, "person", "query { person(id: 1) { name } }\n")
    GraphWeaver.generate!

    expect(Dir).not_to exist File.join(output(:pets), "types")
    expect(Dir).to exist output(:pets)
  end

  # the default graph is the settings, so an app that never calls .graph is
  # exactly where it was
  it "leaves an app with no declared graph alone" do
    expect(GraphWeaver.graphs.size).to eq 1
    expect(GraphWeaver.graphs.first.registry).to be GraphWeaver::Codegen.registry
  end
end
