# typed: ignore — exercises eval-defined constants
require "bigdecimal"
require "graph_weaver/testing"
require "rake"
require "stringio"
require "tmpdir"

# An app with more than one schema. The top-level settings are the one graph
# every single-schema app already has; GraphWeaver.graph declares the others,
# and every entry point walks the list.
describe "GraphWeaver.graph" do
  # a sibling schema that shares nothing with Demo but the shape of the problem
  BILLING_SDL = <<~SDL
    scalar Money
    type Invoice { id: ID!, total: Money! }
    type Query { invoice(id: ID!): Invoice }
  SDL

  around do |example|
    Dir.mktmpdir do |dir|
      @dir = dir
      example.run
    ensure
      GraphWeaver.reset_graphs!
      GraphWeaver::Codegen.reset_registrations!
    end
  end

  # where each graph's queries and output live under the tmpdir
  def write_query(graph, name, source)
    dir = File.join(@dir, graph.to_s, "queries")
    FileUtils.mkdir_p(dir)
    File.write(File.join(dir, "#{name}.graphql"), source)
    dir
  end

  def output(graph) = File.join(@dir, graph.to_s, "generated")

  # the task as rake runs it, stdout captured
  def run_task(name)
    previous, Rake.application = Rake.application, RakeHarness.application
    RakeHarness.application.tasks.each(&:reenable)
    out = StringIO.new
    $stdout = out
    RakeHarness.application["graph_weaver:#{name}"].invoke
    out.string
  ensure
    $stdout = STDOUT
    Rake.application = previous
  end

  def billing_schema = File.join(@dir, "billing.graphql").tap { |p| File.write(p, BILLING_SDL) }

  # the two graphs the rest of the examples share: same file name in both, so
  # only the namespaces keep them apart
  def two_graphs(namespace: true)
    write_query(:pets, "person", "query { person(id: 1) { birthday pets { species } } }\n")
    write_query(:billing, "person", "query { invoice(id: 1) { id total } }\n")

    GraphWeaver.graph :pets,
      schema: Demo::Schema, queries: File.join(@dir, "pets/queries"), output: output(:pets),
      client: Demo::Schema, namespace: (namespace ? "Pets" : nil)
    GraphWeaver.graph :billing,
      schema: billing_schema, queries: File.join(@dir, "billing/queries"), output: output(:billing),
      namespace: (namespace ? "Billing" : nil) do
        register_scalar "Money", BigDecimal, requires: "bigdecimal"
      end
  end

  it "generates each graph into its own output, under its own namespace" do
    two_graphs
    GraphWeaver.generate!

    pets = File.read(File.join(output(:pets), "person_query.rb"))
    billing = File.read(File.join(output(:billing), "person_query.rb"))
    expect(pets).to include("module Pets::PersonQuery")
    expect(billing).to include("module Billing::PersonQuery")
    # the namespace carries the shared types module too — two schemas both
    # hoisting into ::GraphQLTypes is a guaranteed collision, not a chance one
    expect(File.read(File.join(output(:pets), "types.rb"))).to include("module Pets::GraphQLTypes")
  end

  it "keeps a graph's registrations out of every other graph" do
    two_graphs
    GraphWeaver.generate!

    # billing's block registered Money; pets never saw it, and neither did the
    # default graph an initializer writes to
    expect(File.read(File.join(output(:billing), "person_query.rb"))).to include("BigDecimal")
    expect(GraphWeaver::Codegen.scalar_registry).not_to have_key("Money")
  end

  it "refuses two graphs whose files generate the same module, naming both" do
    two_graphs(namespace: false)

    expect { GraphWeaver.generate! }.to raise_error(GraphWeaver::Error, /PersonQuery.*namespace:/m)
  end

  it "reports every graph's changed files and unmatched registrations in one run" do
    two_graphs
    GraphWeaver.graph :extra,
      schema: billing_schema, queries: File.join(@dir, "billing/queries"), output: output(:extra),
      namespace: "Extra" do
        register_scalar "Doubloon", String
      end
    GraphWeaver.generate!

    expect(GraphWeaver.changed_files.grep(/pets/)).not_to be_empty
    expect(GraphWeaver.changed_files.grep(/billing/)).not_to be_empty
    expect(GraphWeaver.unmatched_registrations.join("\n")).to include("Doubloon")
    # scoping is what makes that list short: Money matches the schema it was
    # registered against, so it isn't in it
    expect(GraphWeaver.unmatched_registrations.join("\n")).not_to include("Money")
  end

  it "names the stale graph when verify fails" do
    two_graphs
    GraphWeaver.generate!
    File.write(File.join(output(:billing), "person_query.rb"), "# Generated by GraphWeaver\n")

    expect { GraphWeaver.verify_generated! }.to raise_error(GraphWeaver::Error, /billing/)
  end

  it "checks every graph's queries against its own schema" do
    two_graphs
    write_query(:billing, "broken", "query { invoice(id: 1) { nope } }\n")

    failures = GraphWeaver.check_queries
    expect(failures.keys.grep(/broken/)).not_to be_empty
    # pets' query validates against Demo, not against billing
    expect(failures.keys.grep(/pets/)).to be_empty
  end

  it "loads every graph's generated modules" do
    two_graphs
    GraphWeaver.generate!

    expect(GraphWeaver.load_generated!.grep(/person_query/).size).to eq 2
    expect(defined?(Pets::PersonQuery)).to eq "constant"
    expect(defined?(Billing::PersonQuery)).to eq "constant"
  end

  it "bakes each graph's client into its own modules" do
    two_graphs
    GraphWeaver.generate!

    expect(File.read(File.join(output(:pets), "person_query.rb"))).to include("Demo::Schema")
    expect(File.read(File.join(output(:billing), "person_query.rb"))).not_to include("DEFAULT_CLIENT")
  end

  # `rake -T` is baked before :environment, so the task list can't name the
  # graphs an initializer declared — this is the task that can.
  it "lists every graph, and what rake generate covers" do
    two_graphs
    listed = run_task("graphs")
    expect(listed).to include("pets", "billing", "Pets", "Billing")

    expect(run_task("generate")).to match(/wrote.*pets.*\n(.*\n)*.*billing/)
  end

  # A fake fabricates a wire value from the scalar registrations — so with two
  # graphs it has to use the ones the module it is answering was generated
  # with, or it hands a generated cast a value that cast can't read.
  it "fabricates a scalar the way the graph that owns the schema reads it" do
    schema = GraphQL::Schema.from_definition(BILLING_SDL)
    GraphWeaver.graph :billing, schema:, queries: File.join(@dir, "billing/queries"),
      output: output(:billing), namespace: "Billing" do
        register_scalar "Money", Date
      end

    fake = GraphWeaver::Testing::FakeClient.new(schema:)
    total = fake.execute("query { invoice(id: 1) { total } }").dig("data", "invoice", "total")

    expect { Date.iso8601(total) }.not_to raise_error
  end

  # graphs are declared in one initializer and scalars registered in another,
  # so a graph that copied the top-level registrations when it was DECLARED
  # would depend on which of the two ran first
  it "takes the top-level registrations as they are when it generates" do
    two_graphs
    GraphWeaver.register_scalar("Date", String, cast: :itself, serialize: :itself)
    GraphWeaver.generate!

    expect(File.read(File.join(output(:pets), "person_query.rb"))).not_to include("Date.iso8601")
  end

  # the default graph is the settings, so an app that never calls .graph is
  # exactly where it was
  it "leaves an app with no declared graph alone" do
    expect(GraphWeaver.graphs.size).to eq 1
    expect(GraphWeaver.graphs.first.registry).to be GraphWeaver::Codegen.registry
  end
end
