# typed: strict

# Generated by GraphWeaver 0.7.6 — do not edit. The modules this graph's
# extend_type blocks mint, declared so `srb tc` can resolve the includes
# in the generated code. Ruby never loads an .rbi; the registrations do
# the real work.

module GraphWeaver::TypeHelpers; end
module GraphWeaver::TypeHelpers::Pet; end
